// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tags/v1/tags.proto

package tagsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTagsRequest) Reset() {
	*x = GetAllTagsRequest{}
	mi := &file_tags_v1_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTagsRequest) ProtoMessage() {}

func (x *GetAllTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tags_v1_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTagsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTagsRequest) Descriptor() ([]byte, []int) {
	return file_tags_v1_tags_proto_rawDescGZIP(), []int{0}
}

type GetAllTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTagsResponse) Reset() {
	*x = GetAllTagsResponse{}
	mi := &file_tags_v1_tags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTagsResponse) ProtoMessage() {}

func (x *GetAllTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tags_v1_tags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTagsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTagsResponse) Descriptor() ([]byte, []int) {
	return file_tags_v1_tags_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_tags_v1_tags_proto protoreflect.FileDescriptor

const file_tags_v1_tags_proto_rawDesc = "" +
	"\n" +
	"\x12tags/v1/tags.proto\x12\atags.v1\"\x13\n" +
	"\x11GetAllTagsRequest\"(\n" +
	"\x12GetAllTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2T\n" +
	"\vTagsService\x12E\n" +
	"\n" +
	"GetAllTags\x12\x1a.tags.v1.GetAllTagsRequest\x1a\x1b.tags.v1.GetAllTagsResponseB2Z0github.com/maxischmaxi/ljtime-api/tags/v1;tagsv1b\x06proto3"

var (
	file_tags_v1_tags_proto_rawDescOnce sync.Once
	file_tags_v1_tags_proto_rawDescData []byte
)

func file_tags_v1_tags_proto_rawDescGZIP() []byte {
	file_tags_v1_tags_proto_rawDescOnce.Do(func() {
		file_tags_v1_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tags_v1_tags_proto_rawDesc), len(file_tags_v1_tags_proto_rawDesc)))
	})
	return file_tags_v1_tags_proto_rawDescData
}

var file_tags_v1_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tags_v1_tags_proto_goTypes = []any{
	(*GetAllTagsRequest)(nil),  // 0: tags.v1.GetAllTagsRequest
	(*GetAllTagsResponse)(nil), // 1: tags.v1.GetAllTagsResponse
}
var file_tags_v1_tags_proto_depIdxs = []int32{
	0, // 0: tags.v1.TagsService.GetAllTags:input_type -> tags.v1.GetAllTagsRequest
	1, // 1: tags.v1.TagsService.GetAllTags:output_type -> tags.v1.GetAllTagsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tags_v1_tags_proto_init() }
func file_tags_v1_tags_proto_init() {
	if File_tags_v1_tags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tags_v1_tags_proto_rawDesc), len(file_tags_v1_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tags_v1_tags_proto_goTypes,
		DependencyIndexes: file_tags_v1_tags_proto_depIdxs,
		MessageInfos:      file_tags_v1_tags_proto_msgTypes,
	}.Build()
	File_tags_v1_tags_proto = out.File
	file_tags_v1_tags_proto_goTypes = nil
	file_tags_v1_tags_proto_depIdxs = nil
}
