// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user/v1/user.proto

package userv1

import (
	v1 "github.com/maxischmaxi/ljtime-api/customer/v1"
	v11 "github.com/maxischmaxi/ljtime-api/org/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmploymentState int32

const (
	EmploymentState_EMPLOYMENT_STATE_UNSPECIFIED EmploymentState = 0
	EmploymentState_EMPLOYMENT_STATE_ACTIVE      EmploymentState = 1
	EmploymentState_EMPLOYMENT_STATE_INACTIVE    EmploymentState = 2
)

// Enum value maps for EmploymentState.
var (
	EmploymentState_name = map[int32]string{
		0: "EMPLOYMENT_STATE_UNSPECIFIED",
		1: "EMPLOYMENT_STATE_ACTIVE",
		2: "EMPLOYMENT_STATE_INACTIVE",
	}
	EmploymentState_value = map[string]int32{
		"EMPLOYMENT_STATE_UNSPECIFIED": 0,
		"EMPLOYMENT_STATE_ACTIVE":      1,
		"EMPLOYMENT_STATE_INACTIVE":    2,
	}
)

func (x EmploymentState) Enum() *EmploymentState {
	p := new(EmploymentState)
	*p = x
	return p
}

func (x EmploymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmploymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (EmploymentState) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x EmploymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmploymentState.Descriptor instead.
func (EmploymentState) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

type VacationRequestStatus int32

const (
	VacationRequestStatus_VACATION_REQUEST_STATUS_UNSPECIFIED VacationRequestStatus = 0
	VacationRequestStatus_VACATION_REQUEST_STATUS_PENDING     VacationRequestStatus = 1
	VacationRequestStatus_VACATION_REQUEST_STATUS_APPROVED    VacationRequestStatus = 2
	VacationRequestStatus_VACATION_REQUEST_STATUS_REJECTED    VacationRequestStatus = 3
)

// Enum value maps for VacationRequestStatus.
var (
	VacationRequestStatus_name = map[int32]string{
		0: "VACATION_REQUEST_STATUS_UNSPECIFIED",
		1: "VACATION_REQUEST_STATUS_PENDING",
		2: "VACATION_REQUEST_STATUS_APPROVED",
		3: "VACATION_REQUEST_STATUS_REJECTED",
	}
	VacationRequestStatus_value = map[string]int32{
		"VACATION_REQUEST_STATUS_UNSPECIFIED": 0,
		"VACATION_REQUEST_STATUS_PENDING":     1,
		"VACATION_REQUEST_STATUS_APPROVED":    2,
		"VACATION_REQUEST_STATUS_REJECTED":    3,
	}
)

func (x VacationRequestStatus) Enum() *VacationRequestStatus {
	p := new(VacationRequestStatus)
	*p = x
	return p
}

func (x VacationRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VacationRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[1].Descriptor()
}

func (VacationRequestStatus) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[1]
}

func (x VacationRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VacationRequestStatus.Descriptor instead.
func (VacationRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

type VacationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     int64                  `protobuf:"varint,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       int64                  `protobuf:"varint,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Days          int32                  `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Status        VacationRequestStatus  `protobuf:"varint,5,opt,name=status,proto3,enum=user.v1.VacationRequestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacationRequest) Reset() {
	*x = VacationRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacationRequest) ProtoMessage() {}

func (x *VacationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacationRequest.ProtoReflect.Descriptor instead.
func (*VacationRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *VacationRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *VacationRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *VacationRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *VacationRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *VacationRequest) GetStatus() VacationRequestStatus {
	if x != nil {
		return x.Status
	}
	return VacationRequestStatus_VACATION_REQUEST_STATUS_UNSPECIFIED
}

type CreateUserVacation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year              int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Days              int32                  `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	SpecialDays       int32                  `protobuf:"varint,4,opt,name=special_days,json=specialDays,proto3" json:"special_days,omitempty"`
	SickDaysTaken     int32                  `protobuf:"varint,5,opt,name=sick_days_taken,json=sickDaysTaken,proto3" json:"sick_days_taken,omitempty"`
	VacationDaysTaken int32                  `protobuf:"varint,6,opt,name=vacation_days_taken,json=vacationDaysTaken,proto3" json:"vacation_days_taken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserVacation) Reset() {
	*x = CreateUserVacation{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserVacation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserVacation) ProtoMessage() {}

func (x *CreateUserVacation) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserVacation.ProtoReflect.Descriptor instead.
func (*CreateUserVacation) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserVacation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserVacation) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateUserVacation) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *CreateUserVacation) GetSpecialDays() int32 {
	if x != nil {
		return x.SpecialDays
	}
	return 0
}

func (x *CreateUserVacation) GetSickDaysTaken() int32 {
	if x != nil {
		return x.SickDaysTaken
	}
	return 0
}

func (x *CreateUserVacation) GetVacationDaysTaken() int32 {
	if x != nil {
		return x.VacationDaysTaken
	}
	return 0
}

type UserVacation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Year              int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Days              int32                  `protobuf:"varint,4,opt,name=days,proto3" json:"days,omitempty"`
	SpecialDays       int32                  `protobuf:"varint,5,opt,name=special_days,json=specialDays,proto3" json:"special_days,omitempty"`
	SickDaysTaken     int32                  `protobuf:"varint,6,opt,name=sick_days_taken,json=sickDaysTaken,proto3" json:"sick_days_taken,omitempty"`
	VacationDaysTaken int32                  `protobuf:"varint,7,opt,name=vacation_days_taken,json=vacationDaysTaken,proto3" json:"vacation_days_taken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserVacation) Reset() {
	*x = UserVacation{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVacation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVacation) ProtoMessage() {}

func (x *UserVacation) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVacation.ProtoReflect.Descriptor instead.
func (*UserVacation) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserVacation) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UserVacation) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *UserVacation) GetSpecialDays() int32 {
	if x != nil {
		return x.SpecialDays
	}
	return 0
}

func (x *UserVacation) GetSickDaysTaken() int32 {
	if x != nil {
		return x.SickDaysTaken
	}
	return 0
}

func (x *UserVacation) GetVacationDaysTaken() int32 {
	if x != nil {
		return x.VacationDaysTaken
	}
	return 0
}

type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address          *v1.Address            `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ProjectIds       []string               `protobuf:"bytes,5,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	Tags             []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	EmploymentState  EmploymentState        `protobuf:"varint,7,opt,name=employment_state,json=employmentState,proto3,enum=user.v1.EmploymentState" json:"employment_state,omitempty"`
	Vacations        []*UserVacation        `protobuf:"bytes,8,rep,name=vacations,proto3" json:"vacations,omitempty"`
	VacationRequests []*VacationRequest     `protobuf:"bytes,9,rep,name=vacation_requests,json=vacationRequests,proto3" json:"vacation_requests,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OrgIds           []string               `protobuf:"bytes,13,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`
	FirebaseUid      string                 `protobuf:"bytes,14,opt,name=firebase_uid,json=firebaseUid,proto3" json:"firebase_uid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAddress() *v1.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetEmploymentState() EmploymentState {
	if x != nil {
		return x.EmploymentState
	}
	return EmploymentState_EMPLOYMENT_STATE_UNSPECIFIED
}

func (x *User) GetVacations() []*UserVacation {
	if x != nil {
		return x.Vacations
	}
	return nil
}

func (x *User) GetVacationRequests() []*VacationRequest {
	if x != nil {
		return x.VacationRequests
	}
	return nil
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *User) GetOrgIds() []string {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *User) GetFirebaseUid() string {
	if x != nil {
		return x.FirebaseUid
	}
	return ""
}

type CreateUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address         *v1.Address            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ProjectIds      []string               `protobuf:"bytes,4,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	Tags            []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	EmploymentState EmploymentState        `protobuf:"varint,6,opt,name=employment_state,json=employmentState,proto3,enum=user.v1.EmploymentState" json:"employment_state,omitempty"`
	Vacations       []*CreateUserVacation  `protobuf:"bytes,7,rep,name=vacations,proto3" json:"vacations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUser) Reset() {
	*x = CreateUser{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUser) ProtoMessage() {}

func (x *CreateUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUser.ProtoReflect.Descriptor instead.
func (*CreateUser) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUser) GetAddress() *v1.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateUser) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

func (x *CreateUser) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateUser) GetEmploymentState() EmploymentState {
	if x != nil {
		return x.EmploymentState
	}
	return EmploymentState_EMPLOYMENT_STATE_UNSPECIFIED
}

func (x *CreateUser) GetVacations() []*CreateUserVacation {
	if x != nil {
		return x.Vacations
	}
	return nil
}

type UpdateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       *v1.Address            `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ProjectIds    []string               `protobuf:"bytes,5,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUser) Reset() {
	*x = UpdateUser{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUser) ProtoMessage() {}

func (x *UpdateUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUser.ProtoReflect.Descriptor instead.
func (*UpdateUser) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUser) GetAddress() *v1.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UpdateUser) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

func (x *UpdateUser) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Orgs          []*v11.Org             `protobuf:"bytes,2,rep,name=orgs,proto3" json:"orgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserByIdResponse) GetOrgs() []*v11.Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *CreateUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserRequest) GetUser() *CreateUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *UpdateUser            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *UpdateUser {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Orgs          []*v11.Org             `protobuf:"bytes,2,rep,name=orgs,proto3" json:"orgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailResponse) Reset() {
	*x = GetUserByEmailResponse{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailResponse) ProtoMessage() {}

func (x *GetUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserByEmailResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserByEmailResponse) GetOrgs() []*v11.Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type RemoveUserFromOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromOrgRequest) Reset() {
	*x = RemoveUserFromOrgRequest{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromOrgRequest) ProtoMessage() {}

func (x *RemoveUserFromOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromOrgRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromOrgRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveUserFromOrgRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveUserFromOrgRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type RemoveUserFromOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromOrgResponse) Reset() {
	*x = RemoveUserFromOrgResponse{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromOrgResponse) ProtoMessage() {}

func (x *RemoveUserFromOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromOrgResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromOrgResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

type SetUserActiveStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         EmploymentState        `protobuf:"varint,1,opt,name=state,proto3,enum=user.v1.EmploymentState" json:"state,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserActiveStateRequest) Reset() {
	*x = SetUserActiveStateRequest{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserActiveStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserActiveStateRequest) ProtoMessage() {}

func (x *SetUserActiveStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserActiveStateRequest.ProtoReflect.Descriptor instead.
func (*SetUserActiveStateRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *SetUserActiveStateRequest) GetState() EmploymentState {
	if x != nil {
		return x.State
	}
	return EmploymentState_EMPLOYMENT_STATE_UNSPECIFIED
}

func (x *SetUserActiveStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetUserActiveStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         EmploymentState        `protobuf:"varint,1,opt,name=state,proto3,enum=user.v1.EmploymentState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserActiveStateResponse) Reset() {
	*x = SetUserActiveStateResponse{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserActiveStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserActiveStateResponse) ProtoMessage() {}

func (x *SetUserActiveStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserActiveStateResponse.ProtoReflect.Descriptor instead.
func (*SetUserActiveStateResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *SetUserActiveStateResponse) GetState() EmploymentState {
	if x != nil {
		return x.State
	}
	return EmploymentState_EMPLOYMENT_STATE_UNSPECIFIED
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1acustomer/v1/customer.proto\x1a\x10org/v1/org.proto\"\xb1\x01\n" +
	"\x0fVacationRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\x03R\aendDate\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04days\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.user.v1.VacationRequestStatusR\x06status\"\xd0\x01\n" +
	"\x12CreateUserVacation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04days\x12!\n" +
	"\fspecial_days\x18\x04 \x01(\x05R\vspecialDays\x12&\n" +
	"\x0fsick_days_taken\x18\x05 \x01(\x05R\rsickDaysTaken\x12.\n" +
	"\x13vacation_days_taken\x18\x06 \x01(\x05R\x11vacationDaysTaken\"\xb1\x01\n" +
	"\fUserVacation\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x12\n" +
	"\x04days\x18\x04 \x01(\x05R\x04days\x12!\n" +
	"\fspecial_days\x18\x05 \x01(\x05R\vspecialDays\x12&\n" +
	"\x0fsick_days_taken\x18\x06 \x01(\x05R\rsickDaysTaken\x12.\n" +
	"\x13vacation_days_taken\x18\a \x01(\x05R\x11vacationDaysTaken\"\xe0\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\aaddress\x18\x04 \x01(\v2\x14.customer.v1.AddressR\aaddress\x12\x1f\n" +
	"\vproject_ids\x18\x05 \x03(\tR\n" +
	"projectIds\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12C\n" +
	"\x10employment_state\x18\a \x01(\x0e2\x18.user.v1.EmploymentStateR\x0femploymentState\x123\n" +
	"\tvacations\x18\b \x03(\v2\x15.user.v1.UserVacationR\tvacations\x12E\n" +
	"\x11vacation_requests\x18\t \x03(\v2\x18.user.v1.VacationRequestR\x10vacationRequests\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x17\n" +
	"\aorg_ids\x18\r \x03(\tR\x06orgIds\x12!\n" +
	"\ffirebase_uid\x18\x0e \x01(\tR\vfirebaseUid\"\x9b\x02\n" +
	"\n" +
	"CreateUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\aaddress\x18\x03 \x01(\v2\x14.customer.v1.AddressR\aaddress\x12\x1f\n" +
	"\vproject_ids\x18\x04 \x03(\tR\n" +
	"projectIds\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12C\n" +
	"\x10employment_state\x18\x06 \x01(\x0e2\x18.user.v1.EmploymentStateR\x0femploymentState\x129\n" +
	"\tvacations\x18\a \x03(\v2\x1b.user.v1.CreateUserVacationR\tvacations\"\x85\x01\n" +
	"\n" +
	"UpdateUser\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\aaddress\x18\x04 \x01(\v2\x14.customer.v1.AddressR\aaddress\x12\x1f\n" +
	"\vproject_ids\x18\x05 \x03(\tR\n" +
	"projectIds\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x13GetUserByIdResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12\x1f\n" +
	"\x04orgs\x18\x02 \x03(\v2\v.org.v1.OrgR\x04orgs\"\x14\n" +
	"\x12GetAllUsersRequest\":\n" +
	"\x13GetAllUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.v1.UserR\x05users\"S\n" +
	"\x11CreateUserRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.user.v1.CreateUserR\x04user\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"7\n" +
	"\x12CreateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"L\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04user\x18\x02 \x01(\v2\x13.user.v1.UpdateUserR\x04user\"7\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\\\n" +
	"\x16GetUserByEmailResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12\x1f\n" +
	"\x04orgs\x18\x02 \x03(\v2\v.org.v1.OrgR\x04orgs\"J\n" +
	"\x18RemoveUserFromOrgRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"\x1b\n" +
	"\x19RemoveUserFromOrgResponse\"[\n" +
	"\x19SetUserActiveStateRequest\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.user.v1.EmploymentStateR\x05state\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"L\n" +
	"\x1aSetUserActiveStateResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.user.v1.EmploymentStateR\x05state*o\n" +
	"\x0fEmploymentState\x12 \n" +
	"\x1cEMPLOYMENT_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EMPLOYMENT_STATE_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19EMPLOYMENT_STATE_INACTIVE\x10\x02*\xb1\x01\n" +
	"\x15VacationRequestStatus\x12'\n" +
	"#VACATION_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fVACATION_REQUEST_STATUS_PENDING\x10\x01\x12$\n" +
	" VACATION_REQUEST_STATUS_APPROVED\x10\x02\x12$\n" +
	" VACATION_REQUEST_STATUS_REJECTED\x10\x032\xbd\x04\n" +
	"\vUserService\x12H\n" +
	"\vGetUserById\x12\x1b.user.v1.GetUserByIdRequest\x1a\x1c.user.v1.GetUserByIdResponse\x12Q\n" +
	"\x0eGetUserByEmail\x12\x1e.user.v1.GetUserByEmailRequest\x1a\x1f.user.v1.GetUserByEmailResponse\x12H\n" +
	"\vGetAllUsers\x12\x1b.user.v1.GetAllUsersRequest\x1a\x1c.user.v1.GetAllUsersResponse\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\x12E\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\x12Z\n" +
	"\x11RemoveUserFromOrg\x12!.user.v1.RemoveUserFromOrgRequest\x1a\".user.v1.RemoveUserFromOrgResponse\x12]\n" +
	"\x12SetUserActiveState\x12\".user.v1.SetUserActiveStateRequest\x1a#.user.v1.SetUserActiveStateResponseB2Z0github.com/maxischmaxi/ljtime-api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_v1_user_proto_goTypes = []any{
	(EmploymentState)(0),               // 0: user.v1.EmploymentState
	(VacationRequestStatus)(0),         // 1: user.v1.VacationRequestStatus
	(*VacationRequest)(nil),            // 2: user.v1.VacationRequest
	(*CreateUserVacation)(nil),         // 3: user.v1.CreateUserVacation
	(*UserVacation)(nil),               // 4: user.v1.UserVacation
	(*User)(nil),                       // 5: user.v1.User
	(*CreateUser)(nil),                 // 6: user.v1.CreateUser
	(*UpdateUser)(nil),                 // 7: user.v1.UpdateUser
	(*GetUserByIdRequest)(nil),         // 8: user.v1.GetUserByIdRequest
	(*GetUserByIdResponse)(nil),        // 9: user.v1.GetUserByIdResponse
	(*GetAllUsersRequest)(nil),         // 10: user.v1.GetAllUsersRequest
	(*GetAllUsersResponse)(nil),        // 11: user.v1.GetAllUsersResponse
	(*CreateUserRequest)(nil),          // 12: user.v1.CreateUserRequest
	(*CreateUserResponse)(nil),         // 13: user.v1.CreateUserResponse
	(*UpdateUserRequest)(nil),          // 14: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),         // 15: user.v1.UpdateUserResponse
	(*GetUserByEmailRequest)(nil),      // 16: user.v1.GetUserByEmailRequest
	(*GetUserByEmailResponse)(nil),     // 17: user.v1.GetUserByEmailResponse
	(*RemoveUserFromOrgRequest)(nil),   // 18: user.v1.RemoveUserFromOrgRequest
	(*RemoveUserFromOrgResponse)(nil),  // 19: user.v1.RemoveUserFromOrgResponse
	(*SetUserActiveStateRequest)(nil),  // 20: user.v1.SetUserActiveStateRequest
	(*SetUserActiveStateResponse)(nil), // 21: user.v1.SetUserActiveStateResponse
	(*v1.Address)(nil),                 // 22: customer.v1.Address
	(*v11.Org)(nil),                    // 23: org.v1.Org
}
var file_user_v1_user_proto_depIdxs = []int32{
	1,  // 0: user.v1.VacationRequest.status:type_name -> user.v1.VacationRequestStatus
	22, // 1: user.v1.User.address:type_name -> customer.v1.Address
	0,  // 2: user.v1.User.employment_state:type_name -> user.v1.EmploymentState
	4,  // 3: user.v1.User.vacations:type_name -> user.v1.UserVacation
	2,  // 4: user.v1.User.vacation_requests:type_name -> user.v1.VacationRequest
	22, // 5: user.v1.CreateUser.address:type_name -> customer.v1.Address
	0,  // 6: user.v1.CreateUser.employment_state:type_name -> user.v1.EmploymentState
	3,  // 7: user.v1.CreateUser.vacations:type_name -> user.v1.CreateUserVacation
	22, // 8: user.v1.UpdateUser.address:type_name -> customer.v1.Address
	5,  // 9: user.v1.GetUserByIdResponse.user:type_name -> user.v1.User
	23, // 10: user.v1.GetUserByIdResponse.orgs:type_name -> org.v1.Org
	5,  // 11: user.v1.GetAllUsersResponse.users:type_name -> user.v1.User
	6,  // 12: user.v1.CreateUserRequest.user:type_name -> user.v1.CreateUser
	5,  // 13: user.v1.CreateUserResponse.user:type_name -> user.v1.User
	7,  // 14: user.v1.UpdateUserRequest.user:type_name -> user.v1.UpdateUser
	5,  // 15: user.v1.UpdateUserResponse.user:type_name -> user.v1.User
	5,  // 16: user.v1.GetUserByEmailResponse.user:type_name -> user.v1.User
	23, // 17: user.v1.GetUserByEmailResponse.orgs:type_name -> org.v1.Org
	0,  // 18: user.v1.SetUserActiveStateRequest.state:type_name -> user.v1.EmploymentState
	0,  // 19: user.v1.SetUserActiveStateResponse.state:type_name -> user.v1.EmploymentState
	8,  // 20: user.v1.UserService.GetUserById:input_type -> user.v1.GetUserByIdRequest
	16, // 21: user.v1.UserService.GetUserByEmail:input_type -> user.v1.GetUserByEmailRequest
	10, // 22: user.v1.UserService.GetAllUsers:input_type -> user.v1.GetAllUsersRequest
	12, // 23: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	14, // 24: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	18, // 25: user.v1.UserService.RemoveUserFromOrg:input_type -> user.v1.RemoveUserFromOrgRequest
	20, // 26: user.v1.UserService.SetUserActiveState:input_type -> user.v1.SetUserActiveStateRequest
	9,  // 27: user.v1.UserService.GetUserById:output_type -> user.v1.GetUserByIdResponse
	17, // 28: user.v1.UserService.GetUserByEmail:output_type -> user.v1.GetUserByEmailResponse
	11, // 29: user.v1.UserService.GetAllUsers:output_type -> user.v1.GetAllUsersResponse
	13, // 30: user.v1.UserService.CreateUser:output_type -> user.v1.CreateUserResponse
	15, // 31: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	19, // 32: user.v1.UserService.RemoveUserFromOrg:output_type -> user.v1.RemoveUserFromOrgResponse
	21, // 33: user.v1.UserService.SetUserActiveState:output_type -> user.v1.SetUserActiveStateResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
