import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { headers } from "next/headers";
import { ReactNode } from "react";
import { getAuthenticatedAppForUser } from "@/lib/server-auth";
import { User } from "@firebase/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Super Geheime App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  const h = await headers();
  const lng = h.get("x-locale");

  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <html lang={lng ?? "en"} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers initialUser={currentUser?.toJSON() as User}>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
