// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: positions/v1/positions.proto

package positionsv1

import (
	_ "github.com/maxischmaxi/ljtime-api/org/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionUnit int32

const (
	PositionUnit_POSITION_UNIT_UNSPECIFIED   PositionUnit = 0
	PositionUnit_POSITION_UNIT_WEEKS         PositionUnit = 1
	PositionUnit_POSITION_UNIT_MINUTES       PositionUnit = 2
	PositionUnit_POSITION_UNIT_PAUSCHAL      PositionUnit = 3
	PositionUnit_POSITION_UNIT_NIGHT         PositionUnit = 4
	PositionUnit_POSITION_UNIT_QUBIC_METER   PositionUnit = 5
	PositionUnit_POSITION_UNIT_QUADRAT_METER PositionUnit = 6
	PositionUnit_POSITION_UNIT_METER         PositionUnit = 7
	PositionUnit_POSITION_UNIT_LITER         PositionUnit = 8
	PositionUnit_POSITION_UNIT_KM            PositionUnit = 9
	PositionUnit_POSITION_UNIT_CARDBOARDS    PositionUnit = 10
	PositionUnit_POSITION_UNIT_MONTH         PositionUnit = 11
	PositionUnit_POSITION_UNIT_DAY           PositionUnit = 12
	PositionUnit_POSITION_UNIT_PIECE         PositionUnit = 13
	PositionUnit_POSITION_UNIT_HOURS         PositionUnit = 14
)

// Enum value maps for PositionUnit.
var (
	PositionUnit_name = map[int32]string{
		0:  "POSITION_UNIT_UNSPECIFIED",
		1:  "POSITION_UNIT_WEEKS",
		2:  "POSITION_UNIT_MINUTES",
		3:  "POSITION_UNIT_PAUSCHAL",
		4:  "POSITION_UNIT_NIGHT",
		5:  "POSITION_UNIT_QUBIC_METER",
		6:  "POSITION_UNIT_QUADRAT_METER",
		7:  "POSITION_UNIT_METER",
		8:  "POSITION_UNIT_LITER",
		9:  "POSITION_UNIT_KM",
		10: "POSITION_UNIT_CARDBOARDS",
		11: "POSITION_UNIT_MONTH",
		12: "POSITION_UNIT_DAY",
		13: "POSITION_UNIT_PIECE",
		14: "POSITION_UNIT_HOURS",
	}
	PositionUnit_value = map[string]int32{
		"POSITION_UNIT_UNSPECIFIED":   0,
		"POSITION_UNIT_WEEKS":         1,
		"POSITION_UNIT_MINUTES":       2,
		"POSITION_UNIT_PAUSCHAL":      3,
		"POSITION_UNIT_NIGHT":         4,
		"POSITION_UNIT_QUBIC_METER":   5,
		"POSITION_UNIT_QUADRAT_METER": 6,
		"POSITION_UNIT_METER":         7,
		"POSITION_UNIT_LITER":         8,
		"POSITION_UNIT_KM":            9,
		"POSITION_UNIT_CARDBOARDS":    10,
		"POSITION_UNIT_MONTH":         11,
		"POSITION_UNIT_DAY":           12,
		"POSITION_UNIT_PIECE":         13,
		"POSITION_UNIT_HOURS":         14,
	}
)

func (x PositionUnit) Enum() *PositionUnit {
	p := new(PositionUnit)
	*p = x
	return p
}

func (x PositionUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_positions_v1_positions_proto_enumTypes[0].Descriptor()
}

func (PositionUnit) Type() protoreflect.EnumType {
	return &file_positions_v1_positions_proto_enumTypes[0]
}

func (x PositionUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionUnit.Descriptor instead.
func (PositionUnit) EnumDescriptor() ([]byte, []int) {
	return file_positions_v1_positions_proto_rawDescGZIP(), []int{0}
}

type DiscountType int32

const (
	DiscountType_DISCOUNT_TYPE_UNSPECIFIED DiscountType = 0
	DiscountType_DISCOUNT_TYPE_PERCENT     DiscountType = 1
	DiscountType_DISCOUNT_TYPE_FIXED       DiscountType = 2
)

// Enum value maps for DiscountType.
var (
	DiscountType_name = map[int32]string{
		0: "DISCOUNT_TYPE_UNSPECIFIED",
		1: "DISCOUNT_TYPE_PERCENT",
		2: "DISCOUNT_TYPE_FIXED",
	}
	DiscountType_value = map[string]int32{
		"DISCOUNT_TYPE_UNSPECIFIED": 0,
		"DISCOUNT_TYPE_PERCENT":     1,
		"DISCOUNT_TYPE_FIXED":       2,
	}
)

func (x DiscountType) Enum() *DiscountType {
	p := new(DiscountType)
	*p = x
	return p
}

func (x DiscountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscountType) Descriptor() protoreflect.EnumDescriptor {
	return file_positions_v1_positions_proto_enumTypes[1].Descriptor()
}

func (DiscountType) Type() protoreflect.EnumType {
	return &file_positions_v1_positions_proto_enumTypes[1]
}

func (x DiscountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscountType.Descriptor instead.
func (DiscountType) EnumDescriptor() ([]byte, []int) {
	return file_positions_v1_positions_proto_rawDescGZIP(), []int{1}
}

type Discount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          DiscountType           `protobuf:"varint,2,opt,name=type,proto3,enum=positions.v1.DiscountType" json:"type,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discount) Reset() {
	*x = Discount{}
	mi := &file_positions_v1_positions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discount) ProtoMessage() {}

func (x *Discount) ProtoReflect() protoreflect.Message {
	mi := &file_positions_v1_positions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discount.ProtoReflect.Descriptor instead.
func (*Discount) Descriptor() ([]byte, []int) {
	return file_positions_v1_positions_proto_rawDescGZIP(), []int{0}
}

func (x *Discount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Discount) GetType() DiscountType {
	if x != nil {
		return x.Type
	}
	return DiscountType_DISCOUNT_TYPE_UNSPECIFIED
}

func (x *Discount) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreateDiscount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DiscountType           `protobuf:"varint,2,opt,name=type,proto3,enum=positions.v1.DiscountType" json:"type,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiscount) Reset() {
	*x = CreateDiscount{}
	mi := &file_positions_v1_positions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiscount) ProtoMessage() {}

func (x *CreateDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_positions_v1_positions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiscount.ProtoReflect.Descriptor instead.
func (*CreateDiscount) Descriptor() ([]byte, []int) {
	return file_positions_v1_positions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDiscount) GetType() DiscountType {
	if x != nil {
		return x.Type
	}
	return DiscountType_DISCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateDiscount) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Unit          PositionUnit           `protobuf:"varint,6,opt,name=unit,proto3,enum=positions.v1.PositionUnit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_positions_v1_positions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_positions_v1_positions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_positions_v1_positions_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Position) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Position) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Position) GetUnit() PositionUnit {
	if x != nil {
		return x.Unit
	}
	return PositionUnit_POSITION_UNIT_UNSPECIFIED
}

type CreatePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Unit          PositionUnit           `protobuf:"varint,6,opt,name=unit,proto3,enum=positions.v1.PositionUnit" json:"unit,omitempty"`
	Discount      *Discount              `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePosition) Reset() {
	*x = CreatePosition{}
	mi := &file_positions_v1_positions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePosition) ProtoMessage() {}

func (x *CreatePosition) ProtoReflect() protoreflect.Message {
	mi := &file_positions_v1_positions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePosition.ProtoReflect.Descriptor instead.
func (*CreatePosition) Descriptor() ([]byte, []int) {
	return file_positions_v1_positions_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePosition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePosition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePosition) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreatePosition) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePosition) GetUnit() PositionUnit {
	if x != nil {
		return x.Unit
	}
	return PositionUnit_POSITION_UNIT_UNSPECIFIED
}

func (x *CreatePosition) GetDiscount() *Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

var File_positions_v1_positions_proto protoreflect.FileDescriptor

const file_positions_v1_positions_proto_rawDesc = "" +
	"\n" +
	"\x1cpositions/v1/positions.proto\x12\fpositions.v1\x1a\x10org/v1/org.proto\"`\n" +
	"\bDiscount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.positions.v1.DiscountTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\"V\n" +
	"\x0eCreateDiscount\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.positions.v1.DiscountTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\"\xac\x01\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12.\n" +
	"\x04unit\x18\x06 \x01(\x0e2\x1a.positions.v1.PositionUnitR\x04unit\"\xd6\x01\n" +
	"\x0eCreatePosition\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12.\n" +
	"\x04unit\x18\x06 \x01(\x0e2\x1a.positions.v1.PositionUnitR\x04unit\x122\n" +
	"\bdiscount\x18\a \x01(\v2\x16.positions.v1.DiscountR\bdiscount*\x9e\x03\n" +
	"\fPositionUnit\x12\x1d\n" +
	"\x19POSITION_UNIT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POSITION_UNIT_WEEKS\x10\x01\x12\x19\n" +
	"\x15POSITION_UNIT_MINUTES\x10\x02\x12\x1a\n" +
	"\x16POSITION_UNIT_PAUSCHAL\x10\x03\x12\x17\n" +
	"\x13POSITION_UNIT_NIGHT\x10\x04\x12\x1d\n" +
	"\x19POSITION_UNIT_QUBIC_METER\x10\x05\x12\x1f\n" +
	"\x1bPOSITION_UNIT_QUADRAT_METER\x10\x06\x12\x17\n" +
	"\x13POSITION_UNIT_METER\x10\a\x12\x17\n" +
	"\x13POSITION_UNIT_LITER\x10\b\x12\x14\n" +
	"\x10POSITION_UNIT_KM\x10\t\x12\x1c\n" +
	"\x18POSITION_UNIT_CARDBOARDS\x10\n" +
	"\x12\x17\n" +
	"\x13POSITION_UNIT_MONTH\x10\v\x12\x15\n" +
	"\x11POSITION_UNIT_DAY\x10\f\x12\x17\n" +
	"\x13POSITION_UNIT_PIECE\x10\r\x12\x17\n" +
	"\x13POSITION_UNIT_HOURS\x10\x0e*a\n" +
	"\fDiscountType\x12\x1d\n" +
	"\x19DISCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DISCOUNT_TYPE_PERCENT\x10\x01\x12\x17\n" +
	"\x13DISCOUNT_TYPE_FIXED\x10\x02B<Z:github.com/maxischmaxi/ljtime-api/positions/v1;positionsv1b\x06proto3"

var (
	file_positions_v1_positions_proto_rawDescOnce sync.Once
	file_positions_v1_positions_proto_rawDescData []byte
)

func file_positions_v1_positions_proto_rawDescGZIP() []byte {
	file_positions_v1_positions_proto_rawDescOnce.Do(func() {
		file_positions_v1_positions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_positions_v1_positions_proto_rawDesc), len(file_positions_v1_positions_proto_rawDesc)))
	})
	return file_positions_v1_positions_proto_rawDescData
}

var file_positions_v1_positions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_positions_v1_positions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_positions_v1_positions_proto_goTypes = []any{
	(PositionUnit)(0),      // 0: positions.v1.PositionUnit
	(DiscountType)(0),      // 1: positions.v1.DiscountType
	(*Discount)(nil),       // 2: positions.v1.Discount
	(*CreateDiscount)(nil), // 3: positions.v1.CreateDiscount
	(*Position)(nil),       // 4: positions.v1.Position
	(*CreatePosition)(nil), // 5: positions.v1.CreatePosition
}
var file_positions_v1_positions_proto_depIdxs = []int32{
	1, // 0: positions.v1.Discount.type:type_name -> positions.v1.DiscountType
	1, // 1: positions.v1.CreateDiscount.type:type_name -> positions.v1.DiscountType
	0, // 2: positions.v1.Position.unit:type_name -> positions.v1.PositionUnit
	0, // 3: positions.v1.CreatePosition.unit:type_name -> positions.v1.PositionUnit
	2, // 4: positions.v1.CreatePosition.discount:type_name -> positions.v1.Discount
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_positions_v1_positions_proto_init() }
func file_positions_v1_positions_proto_init() {
	if File_positions_v1_positions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_positions_v1_positions_proto_rawDesc), len(file_positions_v1_positions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_positions_v1_positions_proto_goTypes,
		DependencyIndexes: file_positions_v1_positions_proto_depIdxs,
		EnumInfos:         file_positions_v1_positions_proto_enumTypes,
		MessageInfos:      file_positions_v1_positions_proto_msgTypes,
	}.Build()
	File_positions_v1_positions_proto = out.File
	file_positions_v1_positions_proto_goTypes = nil
	file_positions_v1_positions_proto_depIdxs = nil
}
