// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/v1/org.proto

package orgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailProvider int32

const (
	MailProvider_MAIL_PROVIDER_UNSPECIFIED MailProvider = 0
	MailProvider_MAIL_PROVIDER_GMAIL       MailProvider = 1
)

// Enum value maps for MailProvider.
var (
	MailProvider_name = map[int32]string{
		0: "MAIL_PROVIDER_UNSPECIFIED",
		1: "MAIL_PROVIDER_GMAIL",
	}
	MailProvider_value = map[string]int32{
		"MAIL_PROVIDER_UNSPECIFIED": 0,
		"MAIL_PROVIDER_GMAIL":       1,
	}
)

func (x MailProvider) Enum() *MailProvider {
	p := new(MailProvider)
	*p = x
	return p
}

func (x MailProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_org_v1_org_proto_enumTypes[0].Descriptor()
}

func (MailProvider) Type() protoreflect.EnumType {
	return &file_org_v1_org_proto_enumTypes[0]
}

func (x MailProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailProvider.Descriptor instead.
func (MailProvider) EnumDescriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{0}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iban          string                 `protobuf:"bytes,1,opt,name=iban,proto3" json:"iban,omitempty"`
	Bic           string                 `protobuf:"bytes,2,opt,name=bic,proto3" json:"bic,omitempty"`
	BankName      string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_org_v1_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

func (x *Payment) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *Payment) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

type UpdateOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailProvider  MailProvider           `protobuf:"varint,1,opt,name=mail_provider,json=mailProvider,proto3,enum=org.v1.MailProvider" json:"mail_provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrg) Reset() {
	*x = UpdateOrg{}
	mi := &file_org_v1_org_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrg) ProtoMessage() {}

func (x *UpdateOrg) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrg.ProtoReflect.Descriptor instead.
func (*UpdateOrg) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOrg) GetMailProvider() MailProvider {
	if x != nil {
		return x.MailProvider
	}
	return MailProvider_MAIL_PROVIDER_UNSPECIFIED
}

func (x *UpdateOrg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailProvider  MailProvider           `protobuf:"varint,1,opt,name=mail_provider,json=mailProvider,proto3,enum=org.v1.MailProvider" json:"mail_provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrg) Reset() {
	*x = CreateOrg{}
	mi := &file_org_v1_org_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrg) ProtoMessage() {}

func (x *CreateOrg) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrg.ProtoReflect.Descriptor instead.
func (*CreateOrg) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrg) GetMailProvider() MailProvider {
	if x != nil {
		return x.MailProvider
	}
	return MailProvider_MAIL_PROVIDER_UNSPECIFIED
}

func (x *CreateOrg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServiceType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceType) Reset() {
	*x = ServiceType{}
	mi := &file_org_v1_org_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceType) ProtoMessage() {}

func (x *ServiceType) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceType.ProtoReflect.Descriptor instead.
func (*ServiceType) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceType) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type Org struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MailProvider  MailProvider           `protobuf:"varint,2,opt,name=mail_provider,json=mailProvider,proto3,enum=org.v1.MailProvider" json:"mail_provider,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Admins        []string               `protobuf:"bytes,7,rep,name=admins,proto3" json:"admins,omitempty"`
	ServiceTypes  []*ServiceType         `protobuf:"bytes,8,rep,name=service_types,json=serviceTypes,proto3" json:"service_types,omitempty"`
	Payment       *Payment               `protobuf:"bytes,9,opt,name=payment,proto3" json:"payment,omitempty"`
	LegalNotice   string                 `protobuf:"bytes,10,opt,name=legal_notice,json=legalNotice,proto3" json:"legal_notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Org) Reset() {
	*x = Org{}
	mi := &file_org_v1_org_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{4}
}

func (x *Org) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Org) GetMailProvider() MailProvider {
	if x != nil {
		return x.MailProvider
	}
	return MailProvider_MAIL_PROVIDER_UNSPECIFIED
}

func (x *Org) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Org) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Org) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *Org) GetServiceTypes() []*ServiceType {
	if x != nil {
		return x.ServiceTypes
	}
	return nil
}

func (x *Org) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Org) GetLegalNotice() string {
	if x != nil {
		return x.LegalNotice
	}
	return ""
}

type GetOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgRequest) Reset() {
	*x = GetOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgRequest) ProtoMessage() {}

func (x *GetOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgRequest.ProtoReflect.Descriptor instead.
func (*GetOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{5}
}

type GetOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgResponse) Reset() {
	*x = GetOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgResponse) ProtoMessage() {}

func (x *GetOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgResponse.ProtoReflect.Descriptor instead.
func (*GetOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type GetOrgByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgByIdRequest) Reset() {
	*x = GetOrgByIdRequest{}
	mi := &file_org_v1_org_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgByIdRequest) ProtoMessage() {}

func (x *GetOrgByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrgByIdRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrgByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrgByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgByIdResponse) Reset() {
	*x = GetOrgByIdResponse{}
	mi := &file_org_v1_org_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgByIdResponse) ProtoMessage() {}

func (x *GetOrgByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrgByIdResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrgByIdResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type UpdateOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org           *UpdateOrg             `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgRequest) Reset() {
	*x = UpdateOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgRequest) ProtoMessage() {}

func (x *UpdateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrgRequest) GetOrg() *UpdateOrg {
	if x != nil {
		return x.Org
	}
	return nil
}

type UpdateOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgResponse) Reset() {
	*x = UpdateOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgResponse) ProtoMessage() {}

func (x *UpdateOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{10}
}

type CreateOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *CreateOrg             `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgRequest) Reset() {
	*x = CreateOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgRequest) ProtoMessage() {}

func (x *CreateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{11}
}

func (x *CreateOrgRequest) GetOrg() *CreateOrg {
	if x != nil {
		return x.Org
	}
	return nil
}

type CreateOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgResponse) Reset() {
	*x = CreateOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgResponse) ProtoMessage() {}

func (x *CreateOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgResponse.ProtoReflect.Descriptor instead.
func (*CreateOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type DeleteOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgRequest) Reset() {
	*x = DeleteOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgRequest) ProtoMessage() {}

func (x *DeleteOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteOrgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgResponse) Reset() {
	*x = DeleteOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgResponse) ProtoMessage() {}

func (x *DeleteOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteOrgResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAdminToOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminToOrgRequest) Reset() {
	*x = AddAdminToOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminToOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminToOrgRequest) ProtoMessage() {}

func (x *AddAdminToOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminToOrgRequest.ProtoReflect.Descriptor instead.
func (*AddAdminToOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{15}
}

func (x *AddAdminToOrgRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddAdminToOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminToOrgResponse) Reset() {
	*x = AddAdminToOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminToOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminToOrgResponse) ProtoMessage() {}

func (x *AddAdminToOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminToOrgResponse.ProtoReflect.Descriptor instead.
func (*AddAdminToOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{16}
}

type RemoveAdminFromOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminFromOrgRequest) Reset() {
	*x = RemoveAdminFromOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminFromOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminFromOrgRequest) ProtoMessage() {}

func (x *RemoveAdminFromOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminFromOrgRequest.ProtoReflect.Descriptor instead.
func (*RemoveAdminFromOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveAdminFromOrgRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveAdminFromOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminFromOrgResponse) Reset() {
	*x = RemoveAdminFromOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminFromOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminFromOrgResponse) ProtoMessage() {}

func (x *RemoveAdminFromOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminFromOrgResponse.ProtoReflect.Descriptor instead.
func (*RemoveAdminFromOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{18}
}

type InviteEmailToOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteEmailToOrgRequest) Reset() {
	*x = InviteEmailToOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteEmailToOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteEmailToOrgRequest) ProtoMessage() {}

func (x *InviteEmailToOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteEmailToOrgRequest.ProtoReflect.Descriptor instead.
func (*InviteEmailToOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{19}
}

func (x *InviteEmailToOrgRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteEmailToOrgRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type InviteEmailToOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteEmailToOrgResponse) Reset() {
	*x = InviteEmailToOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteEmailToOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteEmailToOrgResponse) ProtoMessage() {}

func (x *InviteEmailToOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteEmailToOrgResponse.ProtoReflect.Descriptor instead.
func (*InviteEmailToOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{20}
}

type AcceptEmailInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	FirebaseUid   string                 `protobuf:"bytes,3,opt,name=firebase_uid,json=firebaseUid,proto3" json:"firebase_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptEmailInviteRequest) Reset() {
	*x = AcceptEmailInviteRequest{}
	mi := &file_org_v1_org_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptEmailInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptEmailInviteRequest) ProtoMessage() {}

func (x *AcceptEmailInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptEmailInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptEmailInviteRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{21}
}

func (x *AcceptEmailInviteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AcceptEmailInviteRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AcceptEmailInviteRequest) GetFirebaseUid() string {
	if x != nil {
		return x.FirebaseUid
	}
	return ""
}

type AcceptEmailInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptEmailInviteResponse) Reset() {
	*x = AcceptEmailInviteResponse{}
	mi := &file_org_v1_org_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptEmailInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptEmailInviteResponse) ProtoMessage() {}

func (x *AcceptEmailInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptEmailInviteResponse.ProtoReflect.Descriptor instead.
func (*AcceptEmailInviteResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{22}
}

type CreateServiceTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceTypeRequest) Reset() {
	*x = CreateServiceTypeRequest{}
	mi := &file_org_v1_org_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTypeRequest) ProtoMessage() {}

func (x *CreateServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{23}
}

func (x *CreateServiceTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceTypeRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type CreateServiceTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceTypeResponse) Reset() {
	*x = CreateServiceTypeResponse{}
	mi := &file_org_v1_org_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTypeResponse) ProtoMessage() {}

func (x *CreateServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{24}
}

type UpdateServiceTypeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ServiceTypeId string                 `protobuf:"bytes,2,opt,name=service_type_id,json=serviceTypeId,proto3" json:"service_type_id,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceTypeStatusRequest) Reset() {
	*x = UpdateServiceTypeStatusRequest{}
	mi := &file_org_v1_org_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceTypeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceTypeStatusRequest) ProtoMessage() {}

func (x *UpdateServiceTypeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceTypeStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceTypeStatusRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateServiceTypeStatusRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateServiceTypeStatusRequest) GetServiceTypeId() string {
	if x != nil {
		return x.ServiceTypeId
	}
	return ""
}

func (x *UpdateServiceTypeStatusRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateServiceTypeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceTypeStatusResponse) Reset() {
	*x = UpdateServiceTypeStatusResponse{}
	mi := &file_org_v1_org_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceTypeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceTypeStatusResponse) ProtoMessage() {}

func (x *UpdateServiceTypeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceTypeStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceTypeStatusResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateServiceTypeStatusResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteServiceTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ServiceTypeId string                 `protobuf:"bytes,2,opt,name=service_type_id,json=serviceTypeId,proto3" json:"service_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceTypeRequest) Reset() {
	*x = DeleteServiceTypeRequest{}
	mi := &file_org_v1_org_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceTypeRequest) ProtoMessage() {}

func (x *DeleteServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteServiceTypeRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteServiceTypeRequest) GetServiceTypeId() string {
	if x != nil {
		return x.ServiceTypeId
	}
	return ""
}

type DeleteServiceTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceTypeResponse) Reset() {
	*x = DeleteServiceTypeResponse{}
	mi := &file_org_v1_org_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceTypeResponse) ProtoMessage() {}

func (x *DeleteServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{28}
}

type SetOrgPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iban          string                 `protobuf:"bytes,1,opt,name=iban,proto3" json:"iban,omitempty"`
	Bic           string                 `protobuf:"bytes,2,opt,name=bic,proto3" json:"bic,omitempty"`
	BankName      string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	LegalNotice   string                 `protobuf:"bytes,4,opt,name=legalNotice,proto3" json:"legalNotice,omitempty"`
	OrgId         string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrgPaymentRequest) Reset() {
	*x = SetOrgPaymentRequest{}
	mi := &file_org_v1_org_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrgPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrgPaymentRequest) ProtoMessage() {}

func (x *SetOrgPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrgPaymentRequest.ProtoReflect.Descriptor instead.
func (*SetOrgPaymentRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{29}
}

func (x *SetOrgPaymentRequest) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

func (x *SetOrgPaymentRequest) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *SetOrgPaymentRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *SetOrgPaymentRequest) GetLegalNotice() string {
	if x != nil {
		return x.LegalNotice
	}
	return ""
}

func (x *SetOrgPaymentRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type SetOrgPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrgPaymentResponse) Reset() {
	*x = SetOrgPaymentResponse{}
	mi := &file_org_v1_org_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrgPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrgPaymentResponse) ProtoMessage() {}

func (x *SetOrgPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrgPaymentResponse.ProtoReflect.Descriptor instead.
func (*SetOrgPaymentResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{30}
}

var File_org_v1_org_proto protoreflect.FileDescriptor

const file_org_v1_org_proto_rawDesc = "" +
	"\n" +
	"\x10org/v1/org.proto\x12\x06org.v1\"L\n" +
	"\aPayment\x12\x12\n" +
	"\x04iban\x18\x01 \x01(\tR\x04iban\x12\x10\n" +
	"\x03bic\x18\x02 \x01(\tR\x03bic\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\"Z\n" +
	"\tUpdateOrg\x129\n" +
	"\rmail_provider\x18\x01 \x01(\x0e2\x14.org.v1.MailProviderR\fmailProvider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Z\n" +
	"\tCreateOrg\x129\n" +
	"\rmail_provider\x18\x01 \x01(\x0e2\x14.org.v1.MailProviderR\fmailProvider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"I\n" +
	"\vServiceType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"\xc2\x02\n" +
	"\x03Org\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\rmail_provider\x18\x02 \x01(\x0e2\x14.org.v1.MailProviderR\fmailProvider\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06admins\x18\a \x03(\tR\x06admins\x128\n" +
	"\rservice_types\x18\b \x03(\v2\x13.org.v1.ServiceTypeR\fserviceTypes\x12)\n" +
	"\apayment\x18\t \x01(\v2\x0f.org.v1.PaymentR\apayment\x12!\n" +
	"\flegal_notice\x18\n" +
	" \x01(\tR\vlegalNotice\"\x0f\n" +
	"\rGetOrgRequest\"/\n" +
	"\x0eGetOrgResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"#\n" +
	"\x11GetOrgByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x12GetOrgByIdResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"G\n" +
	"\x10UpdateOrgRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x03org\x18\x02 \x01(\v2\x11.org.v1.UpdateOrgR\x03org\"\x13\n" +
	"\x11UpdateOrgResponse\"7\n" +
	"\x10CreateOrgRequest\x12#\n" +
	"\x03org\x18\x01 \x01(\v2\x11.org.v1.CreateOrgR\x03org\"2\n" +
	"\x11CreateOrgResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"\"\n" +
	"\x10DeleteOrgRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeleteOrgResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x14AddAdminToOrgRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x17\n" +
	"\x15AddAdminToOrgResponse\"4\n" +
	"\x19RemoveAdminFromOrgRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1c\n" +
	"\x1aRemoveAdminFromOrgResponse\"F\n" +
	"\x17InviteEmailToOrgRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"\x1a\n" +
	"\x18InviteEmailToOrgResponse\"j\n" +
	"\x18AcceptEmailInviteRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12!\n" +
	"\ffirebase_uid\x18\x03 \x01(\tR\vfirebaseUid\"\x1b\n" +
	"\x19AcceptEmailInviteResponse\"E\n" +
	"\x18CreateServiceTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"\x1b\n" +
	"\x19CreateServiceTypeResponse\"w\n" +
	"\x1eUpdateServiceTypeStatusRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12&\n" +
	"\x0fservice_type_id\x18\x02 \x01(\tR\rserviceTypeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"9\n" +
	"\x1fUpdateServiceTypeStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"Y\n" +
	"\x18DeleteServiceTypeRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12&\n" +
	"\x0fservice_type_id\x18\x02 \x01(\tR\rserviceTypeId\"\x1b\n" +
	"\x19DeleteServiceTypeResponse\"\x92\x01\n" +
	"\x14SetOrgPaymentRequest\x12\x12\n" +
	"\x04iban\x18\x01 \x01(\tR\x04iban\x12\x10\n" +
	"\x03bic\x18\x02 \x01(\tR\x03bic\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12 \n" +
	"\vlegalNotice\x18\x04 \x01(\tR\vlegalNotice\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\"\x17\n" +
	"\x15SetOrgPaymentResponse*F\n" +
	"\fMailProvider\x12\x1d\n" +
	"\x19MAIL_PROVIDER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MAIL_PROVIDER_GMAIL\x10\x012\x9a\b\n" +
	"\n" +
	"OrgService\x127\n" +
	"\x06GetOrg\x12\x15.org.v1.GetOrgRequest\x1a\x16.org.v1.GetOrgResponse\x12C\n" +
	"\n" +
	"GetOrgById\x12\x19.org.v1.GetOrgByIdRequest\x1a\x1a.org.v1.GetOrgByIdResponse\x12@\n" +
	"\tUpdateOrg\x12\x18.org.v1.UpdateOrgRequest\x1a\x19.org.v1.UpdateOrgResponse\x12L\n" +
	"\rSetOrgPayment\x12\x1c.org.v1.SetOrgPaymentRequest\x1a\x1d.org.v1.SetOrgPaymentResponse\x12@\n" +
	"\tCreateOrg\x12\x18.org.v1.CreateOrgRequest\x1a\x19.org.v1.CreateOrgResponse\x12@\n" +
	"\tDeleteOrg\x12\x18.org.v1.DeleteOrgRequest\x1a\x19.org.v1.DeleteOrgResponse\x12L\n" +
	"\rAddAdminToOrg\x12\x1c.org.v1.AddAdminToOrgRequest\x1a\x1d.org.v1.AddAdminToOrgResponse\x12[\n" +
	"\x12RemoveAdminFromOrg\x12!.org.v1.RemoveAdminFromOrgRequest\x1a\".org.v1.RemoveAdminFromOrgResponse\x12U\n" +
	"\x10InviteEmailToOrg\x12\x1f.org.v1.InviteEmailToOrgRequest\x1a .org.v1.InviteEmailToOrgResponse\x12X\n" +
	"\x11AcceptEmailInvite\x12 .org.v1.AcceptEmailInviteRequest\x1a!.org.v1.AcceptEmailInviteResponse\x12X\n" +
	"\x11CreateServiceType\x12 .org.v1.CreateServiceTypeRequest\x1a!.org.v1.CreateServiceTypeResponse\x12j\n" +
	"\x17UpdateServiceTypeStatus\x12&.org.v1.UpdateServiceTypeStatusRequest\x1a'.org.v1.UpdateServiceTypeStatusResponse\x12X\n" +
	"\x11DeleteServiceType\x12 .org.v1.DeleteServiceTypeRequest\x1a!.org.v1.DeleteServiceTypeResponseB0Z.github.com/maxischmaxi/ljtime-api/org/v1;orgv1b\x06proto3"

var (
	file_org_v1_org_proto_rawDescOnce sync.Once
	file_org_v1_org_proto_rawDescData []byte
)

func file_org_v1_org_proto_rawDescGZIP() []byte {
	file_org_v1_org_proto_rawDescOnce.Do(func() {
		file_org_v1_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)))
	})
	return file_org_v1_org_proto_rawDescData
}

var file_org_v1_org_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_org_v1_org_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_org_v1_org_proto_goTypes = []any{
	(MailProvider)(0),                       // 0: org.v1.MailProvider
	(*Payment)(nil),                         // 1: org.v1.Payment
	(*UpdateOrg)(nil),                       // 2: org.v1.UpdateOrg
	(*CreateOrg)(nil),                       // 3: org.v1.CreateOrg
	(*ServiceType)(nil),                     // 4: org.v1.ServiceType
	(*Org)(nil),                             // 5: org.v1.Org
	(*GetOrgRequest)(nil),                   // 6: org.v1.GetOrgRequest
	(*GetOrgResponse)(nil),                  // 7: org.v1.GetOrgResponse
	(*GetOrgByIdRequest)(nil),               // 8: org.v1.GetOrgByIdRequest
	(*GetOrgByIdResponse)(nil),              // 9: org.v1.GetOrgByIdResponse
	(*UpdateOrgRequest)(nil),                // 10: org.v1.UpdateOrgRequest
	(*UpdateOrgResponse)(nil),               // 11: org.v1.UpdateOrgResponse
	(*CreateOrgRequest)(nil),                // 12: org.v1.CreateOrgRequest
	(*CreateOrgResponse)(nil),               // 13: org.v1.CreateOrgResponse
	(*DeleteOrgRequest)(nil),                // 14: org.v1.DeleteOrgRequest
	(*DeleteOrgResponse)(nil),               // 15: org.v1.DeleteOrgResponse
	(*AddAdminToOrgRequest)(nil),            // 16: org.v1.AddAdminToOrgRequest
	(*AddAdminToOrgResponse)(nil),           // 17: org.v1.AddAdminToOrgResponse
	(*RemoveAdminFromOrgRequest)(nil),       // 18: org.v1.RemoveAdminFromOrgRequest
	(*RemoveAdminFromOrgResponse)(nil),      // 19: org.v1.RemoveAdminFromOrgResponse
	(*InviteEmailToOrgRequest)(nil),         // 20: org.v1.InviteEmailToOrgRequest
	(*InviteEmailToOrgResponse)(nil),        // 21: org.v1.InviteEmailToOrgResponse
	(*AcceptEmailInviteRequest)(nil),        // 22: org.v1.AcceptEmailInviteRequest
	(*AcceptEmailInviteResponse)(nil),       // 23: org.v1.AcceptEmailInviteResponse
	(*CreateServiceTypeRequest)(nil),        // 24: org.v1.CreateServiceTypeRequest
	(*CreateServiceTypeResponse)(nil),       // 25: org.v1.CreateServiceTypeResponse
	(*UpdateServiceTypeStatusRequest)(nil),  // 26: org.v1.UpdateServiceTypeStatusRequest
	(*UpdateServiceTypeStatusResponse)(nil), // 27: org.v1.UpdateServiceTypeStatusResponse
	(*DeleteServiceTypeRequest)(nil),        // 28: org.v1.DeleteServiceTypeRequest
	(*DeleteServiceTypeResponse)(nil),       // 29: org.v1.DeleteServiceTypeResponse
	(*SetOrgPaymentRequest)(nil),            // 30: org.v1.SetOrgPaymentRequest
	(*SetOrgPaymentResponse)(nil),           // 31: org.v1.SetOrgPaymentResponse
}
var file_org_v1_org_proto_depIdxs = []int32{
	0,  // 0: org.v1.UpdateOrg.mail_provider:type_name -> org.v1.MailProvider
	0,  // 1: org.v1.CreateOrg.mail_provider:type_name -> org.v1.MailProvider
	0,  // 2: org.v1.Org.mail_provider:type_name -> org.v1.MailProvider
	4,  // 3: org.v1.Org.service_types:type_name -> org.v1.ServiceType
	1,  // 4: org.v1.Org.payment:type_name -> org.v1.Payment
	5,  // 5: org.v1.GetOrgResponse.org:type_name -> org.v1.Org
	5,  // 6: org.v1.GetOrgByIdResponse.org:type_name -> org.v1.Org
	2,  // 7: org.v1.UpdateOrgRequest.org:type_name -> org.v1.UpdateOrg
	3,  // 8: org.v1.CreateOrgRequest.org:type_name -> org.v1.CreateOrg
	5,  // 9: org.v1.CreateOrgResponse.org:type_name -> org.v1.Org
	6,  // 10: org.v1.OrgService.GetOrg:input_type -> org.v1.GetOrgRequest
	8,  // 11: org.v1.OrgService.GetOrgById:input_type -> org.v1.GetOrgByIdRequest
	10, // 12: org.v1.OrgService.UpdateOrg:input_type -> org.v1.UpdateOrgRequest
	30, // 13: org.v1.OrgService.SetOrgPayment:input_type -> org.v1.SetOrgPaymentRequest
	12, // 14: org.v1.OrgService.CreateOrg:input_type -> org.v1.CreateOrgRequest
	14, // 15: org.v1.OrgService.DeleteOrg:input_type -> org.v1.DeleteOrgRequest
	16, // 16: org.v1.OrgService.AddAdminToOrg:input_type -> org.v1.AddAdminToOrgRequest
	18, // 17: org.v1.OrgService.RemoveAdminFromOrg:input_type -> org.v1.RemoveAdminFromOrgRequest
	20, // 18: org.v1.OrgService.InviteEmailToOrg:input_type -> org.v1.InviteEmailToOrgRequest
	22, // 19: org.v1.OrgService.AcceptEmailInvite:input_type -> org.v1.AcceptEmailInviteRequest
	24, // 20: org.v1.OrgService.CreateServiceType:input_type -> org.v1.CreateServiceTypeRequest
	26, // 21: org.v1.OrgService.UpdateServiceTypeStatus:input_type -> org.v1.UpdateServiceTypeStatusRequest
	28, // 22: org.v1.OrgService.DeleteServiceType:input_type -> org.v1.DeleteServiceTypeRequest
	7,  // 23: org.v1.OrgService.GetOrg:output_type -> org.v1.GetOrgResponse
	9,  // 24: org.v1.OrgService.GetOrgById:output_type -> org.v1.GetOrgByIdResponse
	11, // 25: org.v1.OrgService.UpdateOrg:output_type -> org.v1.UpdateOrgResponse
	31, // 26: org.v1.OrgService.SetOrgPayment:output_type -> org.v1.SetOrgPaymentResponse
	13, // 27: org.v1.OrgService.CreateOrg:output_type -> org.v1.CreateOrgResponse
	15, // 28: org.v1.OrgService.DeleteOrg:output_type -> org.v1.DeleteOrgResponse
	17, // 29: org.v1.OrgService.AddAdminToOrg:output_type -> org.v1.AddAdminToOrgResponse
	19, // 30: org.v1.OrgService.RemoveAdminFromOrg:output_type -> org.v1.RemoveAdminFromOrgResponse
	21, // 31: org.v1.OrgService.InviteEmailToOrg:output_type -> org.v1.InviteEmailToOrgResponse
	23, // 32: org.v1.OrgService.AcceptEmailInvite:output_type -> org.v1.AcceptEmailInviteResponse
	25, // 33: org.v1.OrgService.CreateServiceType:output_type -> org.v1.CreateServiceTypeResponse
	27, // 34: org.v1.OrgService.UpdateServiceTypeStatus:output_type -> org.v1.UpdateServiceTypeStatusResponse
	29, // 35: org.v1.OrgService.DeleteServiceType:output_type -> org.v1.DeleteServiceTypeResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_org_v1_org_proto_init() }
func file_org_v1_org_proto_init() {
	if File_org_v1_org_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_v1_org_proto_goTypes,
		DependencyIndexes: file_org_v1_org_proto_depIdxs,
		EnumInfos:         file_org_v1_org_proto_enumTypes,
		MessageInfos:      file_org_v1_org_proto_msgTypes,
	}.Build()
	File_org_v1_org_proto = out.File
	file_org_v1_org_proto_goTypes = nil
	file_org_v1_org_proto_depIdxs = nil
}
