// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/v1/org.proto

package orgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailProvider int32

const (
	MailProvider_MAIL_PROVIDER_UNSPECIFIED MailProvider = 0
	MailProvider_MAIL_PROVIDER_GMAIL       MailProvider = 1
)

// Enum value maps for MailProvider.
var (
	MailProvider_name = map[int32]string{
		0: "MAIL_PROVIDER_UNSPECIFIED",
		1: "MAIL_PROVIDER_GMAIL",
	}
	MailProvider_value = map[string]int32{
		"MAIL_PROVIDER_UNSPECIFIED": 0,
		"MAIL_PROVIDER_GMAIL":       1,
	}
)

func (x MailProvider) Enum() *MailProvider {
	p := new(MailProvider)
	*p = x
	return p
}

func (x MailProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_org_v1_org_proto_enumTypes[0].Descriptor()
}

func (MailProvider) Type() protoreflect.EnumType {
	return &file_org_v1_org_proto_enumTypes[0]
}

func (x MailProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailProvider.Descriptor instead.
func (MailProvider) EnumDescriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{0}
}

type UpdateOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	MailProvider  MailProvider           `protobuf:"varint,2,opt,name=mail_provider,json=mailProvider,proto3,enum=org.v1.MailProvider" json:"mail_provider,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrg) Reset() {
	*x = UpdateOrg{}
	mi := &file_org_v1_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrg) ProtoMessage() {}

func (x *UpdateOrg) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrg.ProtoReflect.Descriptor instead.
func (*UpdateOrg) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOrg) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UpdateOrg) GetMailProvider() MailProvider {
	if x != nil {
		return x.MailProvider
	}
	return MailProvider_MAIL_PROVIDER_UNSPECIFIED
}

func (x *UpdateOrg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	MailProvider  MailProvider           `protobuf:"varint,2,opt,name=mail_provider,json=mailProvider,proto3,enum=org.v1.MailProvider" json:"mail_provider,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrg) Reset() {
	*x = CreateOrg{}
	mi := &file_org_v1_org_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrg) ProtoMessage() {}

func (x *CreateOrg) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrg.ProtoReflect.Descriptor instead.
func (*CreateOrg) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrg) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *CreateOrg) GetMailProvider() MailProvider {
	if x != nil {
		return x.MailProvider
	}
	return MailProvider_MAIL_PROVIDER_UNSPECIFIED
}

func (x *CreateOrg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Org struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MailProvider  MailProvider           `protobuf:"varint,2,opt,name=mail_provider,json=mailProvider,proto3,enum=org.v1.MailProvider" json:"mail_provider,omitempty"`
	Users         []string               `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Org) Reset() {
	*x = Org{}
	mi := &file_org_v1_org_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{2}
}

func (x *Org) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Org) GetMailProvider() MailProvider {
	if x != nil {
		return x.MailProvider
	}
	return MailProvider_MAIL_PROVIDER_UNSPECIFIED
}

func (x *Org) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Org) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Org) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgRequest) Reset() {
	*x = GetOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgRequest) ProtoMessage() {}

func (x *GetOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgRequest.ProtoReflect.Descriptor instead.
func (*GetOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{3}
}

type GetOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgResponse) Reset() {
	*x = GetOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgResponse) ProtoMessage() {}

func (x *GetOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgResponse.ProtoReflect.Descriptor instead.
func (*GetOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type GetOrgByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgByIdRequest) Reset() {
	*x = GetOrgByIdRequest{}
	mi := &file_org_v1_org_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgByIdRequest) ProtoMessage() {}

func (x *GetOrgByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrgByIdRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrgByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrgByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgByIdResponse) Reset() {
	*x = GetOrgByIdResponse{}
	mi := &file_org_v1_org_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgByIdResponse) ProtoMessage() {}

func (x *GetOrgByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrgByIdResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrgByIdResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type UpdateOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org           *UpdateOrg             `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgRequest) Reset() {
	*x = UpdateOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgRequest) ProtoMessage() {}

func (x *UpdateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrgRequest) GetOrg() *UpdateOrg {
	if x != nil {
		return x.Org
	}
	return nil
}

type UpdateOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgResponse) Reset() {
	*x = UpdateOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgResponse) ProtoMessage() {}

func (x *UpdateOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type CreateOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *CreateOrg             `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgRequest) Reset() {
	*x = CreateOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgRequest) ProtoMessage() {}

func (x *CreateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrgRequest) GetOrg() *CreateOrg {
	if x != nil {
		return x.Org
	}
	return nil
}

type CreateOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgResponse) Reset() {
	*x = CreateOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgResponse) ProtoMessage() {}

func (x *CreateOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgResponse.ProtoReflect.Descriptor instead.
func (*CreateOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type DeleteOrgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgRequest) Reset() {
	*x = DeleteOrgRequest{}
	mi := &file_org_v1_org_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgRequest) ProtoMessage() {}

func (x *DeleteOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrgRequest) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteOrgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrgResponse) Reset() {
	*x = DeleteOrgResponse{}
	mi := &file_org_v1_org_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrgResponse) ProtoMessage() {}

func (x *DeleteOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrgResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrgResponse) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteOrgResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_org_v1_org_proto protoreflect.FileDescriptor

const file_org_v1_org_proto_rawDesc = "" +
	"\n" +
	"\x10org/v1/org.proto\x12\x06org.v1\"p\n" +
	"\tUpdateOrg\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\x129\n" +
	"\rmail_provider\x18\x02 \x01(\x0e2\x14.org.v1.MailProviderR\fmailProvider\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"p\n" +
	"\tCreateOrg\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\x129\n" +
	"\rmail_provider\x18\x02 \x01(\x0e2\x14.org.v1.MailProviderR\fmailProvider\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xb8\x01\n" +
	"\x03Org\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\rmail_provider\x18\x02 \x01(\x0e2\x14.org.v1.MailProviderR\fmailProvider\x12\x14\n" +
	"\x05users\x18\x03 \x03(\tR\x05users\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\x0f\n" +
	"\rGetOrgRequest\"/\n" +
	"\x0eGetOrgResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"#\n" +
	"\x11GetOrgByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x12GetOrgByIdResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"G\n" +
	"\x10UpdateOrgRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x03org\x18\x02 \x01(\v2\x11.org.v1.UpdateOrgR\x03org\"2\n" +
	"\x11UpdateOrgResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"7\n" +
	"\x10CreateOrgRequest\x12#\n" +
	"\x03org\x18\x01 \x01(\v2\x11.org.v1.CreateOrgR\x03org\"2\n" +
	"\x11CreateOrgResponse\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.org.v1.OrgR\x03org\"\"\n" +
	"\x10DeleteOrgRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeleteOrgResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*F\n" +
	"\fMailProvider\x12\x1d\n" +
	"\x19MAIL_PROVIDER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MAIL_PROVIDER_GMAIL\x10\x012\xd0\x02\n" +
	"\n" +
	"OrgService\x127\n" +
	"\x06GetOrg\x12\x15.org.v1.GetOrgRequest\x1a\x16.org.v1.GetOrgResponse\x12C\n" +
	"\n" +
	"GetOrgById\x12\x19.org.v1.GetOrgByIdRequest\x1a\x1a.org.v1.GetOrgByIdResponse\x12@\n" +
	"\tUpdateOrg\x12\x18.org.v1.UpdateOrgRequest\x1a\x19.org.v1.UpdateOrgResponse\x12@\n" +
	"\tCreateOrg\x12\x18.org.v1.CreateOrgRequest\x1a\x19.org.v1.CreateOrgResponse\x12@\n" +
	"\tDeleteOrg\x12\x18.org.v1.DeleteOrgRequest\x1a\x19.org.v1.DeleteOrgResponseB0Z.github.com/maxischmaxi/ljtime-api/org/v1;orgv1b\x06proto3"

var (
	file_org_v1_org_proto_rawDescOnce sync.Once
	file_org_v1_org_proto_rawDescData []byte
)

func file_org_v1_org_proto_rawDescGZIP() []byte {
	file_org_v1_org_proto_rawDescOnce.Do(func() {
		file_org_v1_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)))
	})
	return file_org_v1_org_proto_rawDescData
}

var file_org_v1_org_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_org_v1_org_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_org_v1_org_proto_goTypes = []any{
	(MailProvider)(0),          // 0: org.v1.MailProvider
	(*UpdateOrg)(nil),          // 1: org.v1.UpdateOrg
	(*CreateOrg)(nil),          // 2: org.v1.CreateOrg
	(*Org)(nil),                // 3: org.v1.Org
	(*GetOrgRequest)(nil),      // 4: org.v1.GetOrgRequest
	(*GetOrgResponse)(nil),     // 5: org.v1.GetOrgResponse
	(*GetOrgByIdRequest)(nil),  // 6: org.v1.GetOrgByIdRequest
	(*GetOrgByIdResponse)(nil), // 7: org.v1.GetOrgByIdResponse
	(*UpdateOrgRequest)(nil),   // 8: org.v1.UpdateOrgRequest
	(*UpdateOrgResponse)(nil),  // 9: org.v1.UpdateOrgResponse
	(*CreateOrgRequest)(nil),   // 10: org.v1.CreateOrgRequest
	(*CreateOrgResponse)(nil),  // 11: org.v1.CreateOrgResponse
	(*DeleteOrgRequest)(nil),   // 12: org.v1.DeleteOrgRequest
	(*DeleteOrgResponse)(nil),  // 13: org.v1.DeleteOrgResponse
}
var file_org_v1_org_proto_depIdxs = []int32{
	0,  // 0: org.v1.UpdateOrg.mail_provider:type_name -> org.v1.MailProvider
	0,  // 1: org.v1.CreateOrg.mail_provider:type_name -> org.v1.MailProvider
	0,  // 2: org.v1.Org.mail_provider:type_name -> org.v1.MailProvider
	3,  // 3: org.v1.GetOrgResponse.org:type_name -> org.v1.Org
	3,  // 4: org.v1.GetOrgByIdResponse.org:type_name -> org.v1.Org
	1,  // 5: org.v1.UpdateOrgRequest.org:type_name -> org.v1.UpdateOrg
	3,  // 6: org.v1.UpdateOrgResponse.org:type_name -> org.v1.Org
	2,  // 7: org.v1.CreateOrgRequest.org:type_name -> org.v1.CreateOrg
	3,  // 8: org.v1.CreateOrgResponse.org:type_name -> org.v1.Org
	4,  // 9: org.v1.OrgService.GetOrg:input_type -> org.v1.GetOrgRequest
	6,  // 10: org.v1.OrgService.GetOrgById:input_type -> org.v1.GetOrgByIdRequest
	8,  // 11: org.v1.OrgService.UpdateOrg:input_type -> org.v1.UpdateOrgRequest
	10, // 12: org.v1.OrgService.CreateOrg:input_type -> org.v1.CreateOrgRequest
	12, // 13: org.v1.OrgService.DeleteOrg:input_type -> org.v1.DeleteOrgRequest
	5,  // 14: org.v1.OrgService.GetOrg:output_type -> org.v1.GetOrgResponse
	7,  // 15: org.v1.OrgService.GetOrgById:output_type -> org.v1.GetOrgByIdResponse
	9,  // 16: org.v1.OrgService.UpdateOrg:output_type -> org.v1.UpdateOrgResponse
	11, // 17: org.v1.OrgService.CreateOrg:output_type -> org.v1.CreateOrgResponse
	13, // 18: org.v1.OrgService.DeleteOrg:output_type -> org.v1.DeleteOrgResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_org_v1_org_proto_init() }
func file_org_v1_org_proto_init() {
	if File_org_v1_org_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_v1_org_proto_goTypes,
		DependencyIndexes: file_org_v1_org_proto_depIdxs,
		EnumInfos:         file_org_v1_org_proto_enumTypes,
		MessageInfos:      file_org_v1_org_proto_msgTypes,
	}.Build()
	File_org_v1_org_proto = out.File
	file_org_v1_org_proto_goTypes = nil
	file_org_v1_org_proto_depIdxs = nil
}
