// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file invoices/v1/invoices.proto (package invoices.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Payment } from "../../org/v1/org_pb";
import { file_org_v1_org } from "../../org/v1/org_pb";
import type { Position } from "../../positions/v1/positions_pb";
import { file_positions_v1_positions } from "../../positions/v1/positions_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file invoices/v1/invoices.proto.
 */
export const file_invoices_v1_invoices: GenFile = /*@__PURE__*/
  fileDesc("ChppbnZvaWNlcy92MS9pbnZvaWNlcy5wcm90bxILaW52b2ljZXMudjEi1gEKB0ludm9pY2USCgoCaWQYASABKAkSEgoKaW52b2ljZV9ubxgCIAEoCRIMCgRub3RlGAMgASgJEhMKC2N1c3RvbWVyX2lkGAQgASgJEikKCXBvc2l0aW9ucxgFIAMoCzIWLnBvc2l0aW9ucy52MS5Qb3NpdGlvbhIZCgxsZWdhbF9ub3RpY2UYBiABKAlIAIgBARIlCgdwYXltZW50GAggASgLMg8ub3JnLnYxLlBheW1lbnRIAYgBAUIPCg1fbGVnYWxfbm90aWNlQgoKCF9wYXltZW50MhEKD0ludm9pY2VzU2VydmljZUI6WjhnaXRodWIuY29tL21heGlzY2htYXhpL2xqdGltZS1hcGkvaW52b2ljZXMvdjE7aW52b2ljZXN2MWIGcHJvdG8z", [file_org_v1_org, file_positions_v1_positions]);

/**
 * @generated from message invoices.v1.Invoice
 */
export type Invoice = Message<"invoices.v1.Invoice"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string invoice_no = 2;
   */
  invoiceNo: string;

  /**
   * @generated from field: string note = 3;
   */
  note: string;

  /**
   * @generated from field: string customer_id = 4;
   */
  customerId: string;

  /**
   * @generated from field: repeated positions.v1.Position positions = 5;
   */
  positions: Position[];

  /**
   * @generated from field: optional string legal_notice = 6;
   */
  legalNotice?: string;

  /**
   * @generated from field: optional org.v1.Payment payment = 8;
   */
  payment?: Payment;
};

/**
 * Describes the message invoices.v1.Invoice.
 * Use `create(InvoiceSchema)` to create a new message.
 */
export const InvoiceSchema: GenMessage<Invoice> = /*@__PURE__*/
  messageDesc(file_invoices_v1_invoices, 0);

/**
 * @generated from service invoices.v1.InvoicesService
 */
export const InvoicesService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_invoices_v1_invoices, 0);

