// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: offers/v1/offers.proto

package offersv1

import (
	v11 "github.com/maxischmaxi/ljtime-api/org/v1"
	v1 "github.com/maxischmaxi/ljtime-api/positions/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfferStatus int32

const (
	OfferStatus_OFFER_STATUS_UNSPECIFIED OfferStatus = 0
	OfferStatus_OFFER_STATUS_DRAFT       OfferStatus = 1
	OfferStatus_OFFER_STATUS_SENT        OfferStatus = 2
	OfferStatus_OFFER_STATUS_READY       OfferStatus = 3
)

// Enum value maps for OfferStatus.
var (
	OfferStatus_name = map[int32]string{
		0: "OFFER_STATUS_UNSPECIFIED",
		1: "OFFER_STATUS_DRAFT",
		2: "OFFER_STATUS_SENT",
		3: "OFFER_STATUS_READY",
	}
	OfferStatus_value = map[string]int32{
		"OFFER_STATUS_UNSPECIFIED": 0,
		"OFFER_STATUS_DRAFT":       1,
		"OFFER_STATUS_SENT":        2,
		"OFFER_STATUS_READY":       3,
	}
)

func (x OfferStatus) Enum() *OfferStatus {
	p := new(OfferStatus)
	*p = x
	return p
}

func (x OfferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_offers_v1_offers_proto_enumTypes[0].Descriptor()
}

func (OfferStatus) Type() protoreflect.EnumType {
	return &file_offers_v1_offers_proto_enumTypes[0]
}

func (x OfferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfferStatus.Descriptor instead.
func (OfferStatus) EnumDescriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{0}
}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfferNo       string                 `protobuf:"bytes,2,opt,name=offer_no,json=offerNo,proto3" json:"offer_no,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	CustomerId    string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Positions     []*v1.Position         `protobuf:"bytes,5,rep,name=positions,proto3" json:"positions,omitempty"`
	LegalNotice   *string                `protobuf:"bytes,6,opt,name=legal_notice,json=legalNotice,proto3,oneof" json:"legal_notice,omitempty"`
	Payment       *v11.Payment           `protobuf:"bytes,7,opt,name=payment,proto3,oneof" json:"payment,omitempty"`
	Discount      *v1.Discount           `protobuf:"bytes,8,opt,name=discount,proto3" json:"discount,omitempty"`
	DateOfIssue   string                 `protobuf:"bytes,9,opt,name=date_of_issue,json=dateOfIssue,proto3" json:"date_of_issue,omitempty"`
	ValidUntil    string                 `protobuf:"bytes,10,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OrgId         string                 `protobuf:"bytes,13,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Status        OfferStatus            `protobuf:"varint,14,opt,name=status,proto3,enum=offers.v1.OfferStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_offers_v1_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Offer) GetOfferNo() string {
	if x != nil {
		return x.OfferNo
	}
	return ""
}

func (x *Offer) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Offer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Offer) GetPositions() []*v1.Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Offer) GetLegalNotice() string {
	if x != nil && x.LegalNotice != nil {
		return *x.LegalNotice
	}
	return ""
}

func (x *Offer) GetPayment() *v11.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Offer) GetDiscount() *v1.Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *Offer) GetDateOfIssue() string {
	if x != nil {
		return x.DateOfIssue
	}
	return ""
}

func (x *Offer) GetValidUntil() string {
	if x != nil {
		return x.ValidUntil
	}
	return ""
}

func (x *Offer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Offer) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Offer) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Offer) GetStatus() OfferStatus {
	if x != nil {
		return x.Status
	}
	return OfferStatus_OFFER_STATUS_UNSPECIFIED
}

type CreateOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferNo       string                 `protobuf:"bytes,1,opt,name=offer_no,json=offerNo,proto3" json:"offer_no,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Positions     []*v1.CreatePosition   `protobuf:"bytes,5,rep,name=positions,proto3" json:"positions,omitempty"`
	LegalNotice   string                 `protobuf:"bytes,6,opt,name=legal_notice,json=legalNotice,proto3" json:"legal_notice,omitempty"`
	Payment       *v11.Payment           `protobuf:"bytes,7,opt,name=payment,proto3,oneof" json:"payment,omitempty"`
	Discount      *v1.CreateDiscount     `protobuf:"bytes,8,opt,name=discount,proto3" json:"discount,omitempty"`
	DateOfIssue   string                 `protobuf:"bytes,9,opt,name=date_of_issue,json=dateOfIssue,proto3" json:"date_of_issue,omitempty"`
	ValidUntil    string                 `protobuf:"bytes,10,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	OrgId         string                 `protobuf:"bytes,11,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Status        OfferStatus            `protobuf:"varint,12,opt,name=status,proto3,enum=offers.v1.OfferStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferRequest) Reset() {
	*x = CreateOfferRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferRequest) ProtoMessage() {}

func (x *CreateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOfferRequest) GetOfferNo() string {
	if x != nil {
		return x.OfferNo
	}
	return ""
}

func (x *CreateOfferRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateOfferRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOfferRequest) GetPositions() []*v1.CreatePosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *CreateOfferRequest) GetLegalNotice() string {
	if x != nil {
		return x.LegalNotice
	}
	return ""
}

func (x *CreateOfferRequest) GetPayment() *v11.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreateOfferRequest) GetDiscount() *v1.CreateDiscount {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *CreateOfferRequest) GetDateOfIssue() string {
	if x != nil {
		return x.DateOfIssue
	}
	return ""
}

func (x *CreateOfferRequest) GetValidUntil() string {
	if x != nil {
		return x.ValidUntil
	}
	return ""
}

func (x *CreateOfferRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateOfferRequest) GetStatus() OfferStatus {
	if x != nil {
		return x.Status
	}
	return OfferStatus_OFFER_STATUS_UNSPECIFIED
}

type CreateOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferResponse) Reset() {
	*x = CreateOfferResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferResponse) ProtoMessage() {}

func (x *CreateOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOfferResponse) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type GetOffersByCustomerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersByCustomerIdRequest) Reset() {
	*x = GetOffersByCustomerIdRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersByCustomerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersByCustomerIdRequest) ProtoMessage() {}

func (x *GetOffersByCustomerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersByCustomerIdRequest.ProtoReflect.Descriptor instead.
func (*GetOffersByCustomerIdRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{3}
}

func (x *GetOffersByCustomerIdRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetOffersByCustomerIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersByCustomerIdResponse) Reset() {
	*x = GetOffersByCustomerIdResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersByCustomerIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersByCustomerIdResponse) ProtoMessage() {}

func (x *GetOffersByCustomerIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersByCustomerIdResponse.ProtoReflect.Descriptor instead.
func (*GetOffersByCustomerIdResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{4}
}

func (x *GetOffersByCustomerIdResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type GetOfferPdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferPdfRequest) Reset() {
	*x = GetOfferPdfRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferPdfRequest) ProtoMessage() {}

func (x *GetOfferPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferPdfRequest.ProtoReflect.Descriptor instead.
func (*GetOfferPdfRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{5}
}

func (x *GetOfferPdfRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

type GetOfferPdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfData       []byte                 `protobuf:"bytes,1,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferPdfResponse) Reset() {
	*x = GetOfferPdfResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferPdfResponse) ProtoMessage() {}

func (x *GetOfferPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferPdfResponse.ProtoReflect.Descriptor instead.
func (*GetOfferPdfResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{6}
}

func (x *GetOfferPdfResponse) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

type GetOffersByOrgIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersByOrgIdRequest) Reset() {
	*x = GetOffersByOrgIdRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersByOrgIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersByOrgIdRequest) ProtoMessage() {}

func (x *GetOffersByOrgIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersByOrgIdRequest.ProtoReflect.Descriptor instead.
func (*GetOffersByOrgIdRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{7}
}

func (x *GetOffersByOrgIdRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type GetOffersByOrgIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersByOrgIdResponse) Reset() {
	*x = GetOffersByOrgIdResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersByOrgIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersByOrgIdResponse) ProtoMessage() {}

func (x *GetOffersByOrgIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersByOrgIdResponse.ProtoReflect.Descriptor instead.
func (*GetOffersByOrgIdResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{8}
}

func (x *GetOffersByOrgIdResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type GetOfferByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferByIdRequest) Reset() {
	*x = GetOfferByIdRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferByIdRequest) ProtoMessage() {}

func (x *GetOfferByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOfferByIdRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{9}
}

func (x *GetOfferByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOfferByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferByIdResponse) Reset() {
	*x = GetOfferByIdResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferByIdResponse) ProtoMessage() {}

func (x *GetOfferByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOfferByIdResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{10}
}

func (x *GetOfferByIdResponse) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type CreateEmptyOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmptyOfferRequest) Reset() {
	*x = CreateEmptyOfferRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmptyOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmptyOfferRequest) ProtoMessage() {}

func (x *CreateEmptyOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmptyOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateEmptyOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{11}
}

func (x *CreateEmptyOfferRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type CreateEmptyOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmptyOfferResponse) Reset() {
	*x = CreateEmptyOfferResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmptyOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmptyOfferResponse) ProtoMessage() {}

func (x *CreateEmptyOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmptyOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateEmptyOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEmptyOfferResponse) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type UpdateOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfferNo       string                 `protobuf:"bytes,2,opt,name=offer_no,json=offerNo,proto3" json:"offer_no,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	CustomerId    string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Positions     []*v1.Position         `protobuf:"bytes,5,rep,name=positions,proto3" json:"positions,omitempty"`
	LegalNotice   *string                `protobuf:"bytes,6,opt,name=legal_notice,json=legalNotice,proto3,oneof" json:"legal_notice,omitempty"`
	Payment       *v11.Payment           `protobuf:"bytes,7,opt,name=payment,proto3,oneof" json:"payment,omitempty"`
	Discount      *v1.Discount           `protobuf:"bytes,8,opt,name=discount,proto3" json:"discount,omitempty"`
	DateOfIssue   string                 `protobuf:"bytes,9,opt,name=date_of_issue,json=dateOfIssue,proto3" json:"date_of_issue,omitempty"`
	ValidUntil    string                 `protobuf:"bytes,10,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Status        OfferStatus            `protobuf:"varint,11,opt,name=status,proto3,enum=offers.v1.OfferStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOfferRequest) Reset() {
	*x = UpdateOfferRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfferRequest) ProtoMessage() {}

func (x *UpdateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfferRequest.ProtoReflect.Descriptor instead.
func (*UpdateOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOfferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOfferRequest) GetOfferNo() string {
	if x != nil {
		return x.OfferNo
	}
	return ""
}

func (x *UpdateOfferRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateOfferRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateOfferRequest) GetPositions() []*v1.Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *UpdateOfferRequest) GetLegalNotice() string {
	if x != nil && x.LegalNotice != nil {
		return *x.LegalNotice
	}
	return ""
}

func (x *UpdateOfferRequest) GetPayment() *v11.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *UpdateOfferRequest) GetDiscount() *v1.Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

func (x *UpdateOfferRequest) GetDateOfIssue() string {
	if x != nil {
		return x.DateOfIssue
	}
	return ""
}

func (x *UpdateOfferRequest) GetValidUntil() string {
	if x != nil {
		return x.ValidUntil
	}
	return ""
}

func (x *UpdateOfferRequest) GetStatus() OfferStatus {
	if x != nil {
		return x.Status
	}
	return OfferStatus_OFFER_STATUS_UNSPECIFIED
}

type UpdateOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOfferResponse) Reset() {
	*x = UpdateOfferResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfferResponse) ProtoMessage() {}

func (x *UpdateOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfferResponse.ProtoReflect.Descriptor instead.
func (*UpdateOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateOfferResponse) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type DeleteOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOfferRequest) Reset() {
	*x = DeleteOfferRequest{}
	mi := &file_offers_v1_offers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfferRequest) ProtoMessage() {}

func (x *DeleteOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfferRequest.ProtoReflect.Descriptor instead.
func (*DeleteOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteOfferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOfferResponse) Reset() {
	*x = DeleteOfferResponse{}
	mi := &file_offers_v1_offers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfferResponse) ProtoMessage() {}

func (x *DeleteOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_v1_offers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfferResponse.ProtoReflect.Descriptor instead.
func (*DeleteOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_v1_offers_proto_rawDescGZIP(), []int{16}
}

var File_offers_v1_offers_proto protoreflect.FileDescriptor

const file_offers_v1_offers_proto_rawDesc = "" +
	"\n" +
	"\x16offers/v1/offers.proto\x12\toffers.v1\x1a\x10org/v1/org.proto\x1a\x1cpositions/v1/positions.proto\"\x90\x04\n" +
	"\x05Offer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\boffer_no\x18\x02 \x01(\tR\aofferNo\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x124\n" +
	"\tpositions\x18\x05 \x03(\v2\x16.positions.v1.PositionR\tpositions\x12&\n" +
	"\flegal_notice\x18\x06 \x01(\tH\x00R\vlegalNotice\x88\x01\x01\x12.\n" +
	"\apayment\x18\a \x01(\v2\x0f.org.v1.PaymentH\x01R\apayment\x88\x01\x01\x122\n" +
	"\bdiscount\x18\b \x01(\v2\x16.positions.v1.DiscountR\bdiscount\x12\"\n" +
	"\rdate_of_issue\x18\t \x01(\tR\vdateOfIssue\x12\x1f\n" +
	"\vvalid_until\x18\n" +
	" \x01(\tR\n" +
	"validUntil\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x15\n" +
	"\x06org_id\x18\r \x01(\tR\x05orgId\x12.\n" +
	"\x06status\x18\x0e \x01(\x0e2\x16.offers.v1.OfferStatusR\x06statusB\x0f\n" +
	"\r_legal_noticeB\n" +
	"\n" +
	"\b_payment\"\xc5\x03\n" +
	"\x12CreateOfferRequest\x12\x19\n" +
	"\boffer_no\x18\x01 \x01(\tR\aofferNo\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12:\n" +
	"\tpositions\x18\x05 \x03(\v2\x1c.positions.v1.CreatePositionR\tpositions\x12!\n" +
	"\flegal_notice\x18\x06 \x01(\tR\vlegalNotice\x12.\n" +
	"\apayment\x18\a \x01(\v2\x0f.org.v1.PaymentH\x00R\apayment\x88\x01\x01\x128\n" +
	"\bdiscount\x18\b \x01(\v2\x1c.positions.v1.CreateDiscountR\bdiscount\x12\"\n" +
	"\rdate_of_issue\x18\t \x01(\tR\vdateOfIssue\x12\x1f\n" +
	"\vvalid_until\x18\n" +
	" \x01(\tR\n" +
	"validUntil\x12\x15\n" +
	"\x06org_id\x18\v \x01(\tR\x05orgId\x12.\n" +
	"\x06status\x18\f \x01(\x0e2\x16.offers.v1.OfferStatusR\x06statusB\n" +
	"\n" +
	"\b_payment\"=\n" +
	"\x13CreateOfferResponse\x12&\n" +
	"\x05offer\x18\x01 \x01(\v2\x10.offers.v1.OfferR\x05offer\"?\n" +
	"\x1cGetOffersByCustomerIdRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"I\n" +
	"\x1dGetOffersByCustomerIdResponse\x12(\n" +
	"\x06offers\x18\x01 \x03(\v2\x10.offers.v1.OfferR\x06offers\"/\n" +
	"\x12GetOfferPdfRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\"0\n" +
	"\x13GetOfferPdfResponse\x12\x19\n" +
	"\bpdf_data\x18\x01 \x01(\fR\apdfData\"0\n" +
	"\x17GetOffersByOrgIdRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"D\n" +
	"\x18GetOffersByOrgIdResponse\x12(\n" +
	"\x06offers\x18\x01 \x03(\v2\x10.offers.v1.OfferR\x06offers\"%\n" +
	"\x13GetOfferByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14GetOfferByIdResponse\x12&\n" +
	"\x05offer\x18\x01 \x01(\v2\x10.offers.v1.OfferR\x05offer\"0\n" +
	"\x17CreateEmptyOfferRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"B\n" +
	"\x18CreateEmptyOfferResponse\x12&\n" +
	"\x05offer\x18\x01 \x01(\v2\x10.offers.v1.OfferR\x05offer\"\xc8\x03\n" +
	"\x12UpdateOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\boffer_no\x18\x02 \x01(\tR\aofferNo\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x124\n" +
	"\tpositions\x18\x05 \x03(\v2\x16.positions.v1.PositionR\tpositions\x12&\n" +
	"\flegal_notice\x18\x06 \x01(\tH\x00R\vlegalNotice\x88\x01\x01\x12.\n" +
	"\apayment\x18\a \x01(\v2\x0f.org.v1.PaymentH\x01R\apayment\x88\x01\x01\x122\n" +
	"\bdiscount\x18\b \x01(\v2\x16.positions.v1.DiscountR\bdiscount\x12\"\n" +
	"\rdate_of_issue\x18\t \x01(\tR\vdateOfIssue\x12\x1f\n" +
	"\vvalid_until\x18\n" +
	" \x01(\tR\n" +
	"validUntil\x12.\n" +
	"\x06status\x18\v \x01(\x0e2\x16.offers.v1.OfferStatusR\x06statusB\x0f\n" +
	"\r_legal_noticeB\n" +
	"\n" +
	"\b_payment\"=\n" +
	"\x13UpdateOfferResponse\x12&\n" +
	"\x05offer\x18\x01 \x01(\v2\x10.offers.v1.OfferR\x05offer\"$\n" +
	"\x12DeleteOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteOfferResponse*r\n" +
	"\vOfferStatus\x12\x1c\n" +
	"\x18OFFER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OFFER_STATUS_DRAFT\x10\x01\x12\x15\n" +
	"\x11OFFER_STATUS_SENT\x10\x02\x12\x16\n" +
	"\x12OFFER_STATUS_READY\x10\x032\xbe\x05\n" +
	"\rOffersService\x12[\n" +
	"\x10GetOffersByOrgId\x12\".offers.v1.GetOffersByOrgIdRequest\x1a#.offers.v1.GetOffersByOrgIdResponse\x12O\n" +
	"\fGetOfferById\x12\x1e.offers.v1.GetOfferByIdRequest\x1a\x1f.offers.v1.GetOfferByIdResponse\x12[\n" +
	"\x10CreateEmptyOffer\x12\".offers.v1.CreateEmptyOfferRequest\x1a#.offers.v1.CreateEmptyOfferResponse\x12L\n" +
	"\vCreateOffer\x12\x1d.offers.v1.CreateOfferRequest\x1a\x1e.offers.v1.CreateOfferResponse\x12j\n" +
	"\x15GetOffersByCustomerId\x12'.offers.v1.GetOffersByCustomerIdRequest\x1a(.offers.v1.GetOffersByCustomerIdResponse\x12L\n" +
	"\vGetOfferPdf\x12\x1d.offers.v1.GetOfferPdfRequest\x1a\x1e.offers.v1.GetOfferPdfResponse\x12L\n" +
	"\vUpdateOffer\x12\x1d.offers.v1.UpdateOfferRequest\x1a\x1e.offers.v1.UpdateOfferResponse\x12L\n" +
	"\vDeleteOffer\x12\x1d.offers.v1.DeleteOfferRequest\x1a\x1e.offers.v1.DeleteOfferResponseB6Z4github.com/maxischmaxi/ljtime-api/offers/v1;offersv1b\x06proto3"

var (
	file_offers_v1_offers_proto_rawDescOnce sync.Once
	file_offers_v1_offers_proto_rawDescData []byte
)

func file_offers_v1_offers_proto_rawDescGZIP() []byte {
	file_offers_v1_offers_proto_rawDescOnce.Do(func() {
		file_offers_v1_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offers_v1_offers_proto_rawDesc), len(file_offers_v1_offers_proto_rawDesc)))
	})
	return file_offers_v1_offers_proto_rawDescData
}

var file_offers_v1_offers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_offers_v1_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_offers_v1_offers_proto_goTypes = []any{
	(OfferStatus)(0),                      // 0: offers.v1.OfferStatus
	(*Offer)(nil),                         // 1: offers.v1.Offer
	(*CreateOfferRequest)(nil),            // 2: offers.v1.CreateOfferRequest
	(*CreateOfferResponse)(nil),           // 3: offers.v1.CreateOfferResponse
	(*GetOffersByCustomerIdRequest)(nil),  // 4: offers.v1.GetOffersByCustomerIdRequest
	(*GetOffersByCustomerIdResponse)(nil), // 5: offers.v1.GetOffersByCustomerIdResponse
	(*GetOfferPdfRequest)(nil),            // 6: offers.v1.GetOfferPdfRequest
	(*GetOfferPdfResponse)(nil),           // 7: offers.v1.GetOfferPdfResponse
	(*GetOffersByOrgIdRequest)(nil),       // 8: offers.v1.GetOffersByOrgIdRequest
	(*GetOffersByOrgIdResponse)(nil),      // 9: offers.v1.GetOffersByOrgIdResponse
	(*GetOfferByIdRequest)(nil),           // 10: offers.v1.GetOfferByIdRequest
	(*GetOfferByIdResponse)(nil),          // 11: offers.v1.GetOfferByIdResponse
	(*CreateEmptyOfferRequest)(nil),       // 12: offers.v1.CreateEmptyOfferRequest
	(*CreateEmptyOfferResponse)(nil),      // 13: offers.v1.CreateEmptyOfferResponse
	(*UpdateOfferRequest)(nil),            // 14: offers.v1.UpdateOfferRequest
	(*UpdateOfferResponse)(nil),           // 15: offers.v1.UpdateOfferResponse
	(*DeleteOfferRequest)(nil),            // 16: offers.v1.DeleteOfferRequest
	(*DeleteOfferResponse)(nil),           // 17: offers.v1.DeleteOfferResponse
	(*v1.Position)(nil),                   // 18: positions.v1.Position
	(*v11.Payment)(nil),                   // 19: org.v1.Payment
	(*v1.Discount)(nil),                   // 20: positions.v1.Discount
	(*v1.CreatePosition)(nil),             // 21: positions.v1.CreatePosition
	(*v1.CreateDiscount)(nil),             // 22: positions.v1.CreateDiscount
}
var file_offers_v1_offers_proto_depIdxs = []int32{
	18, // 0: offers.v1.Offer.positions:type_name -> positions.v1.Position
	19, // 1: offers.v1.Offer.payment:type_name -> org.v1.Payment
	20, // 2: offers.v1.Offer.discount:type_name -> positions.v1.Discount
	0,  // 3: offers.v1.Offer.status:type_name -> offers.v1.OfferStatus
	21, // 4: offers.v1.CreateOfferRequest.positions:type_name -> positions.v1.CreatePosition
	19, // 5: offers.v1.CreateOfferRequest.payment:type_name -> org.v1.Payment
	22, // 6: offers.v1.CreateOfferRequest.discount:type_name -> positions.v1.CreateDiscount
	0,  // 7: offers.v1.CreateOfferRequest.status:type_name -> offers.v1.OfferStatus
	1,  // 8: offers.v1.CreateOfferResponse.offer:type_name -> offers.v1.Offer
	1,  // 9: offers.v1.GetOffersByCustomerIdResponse.offers:type_name -> offers.v1.Offer
	1,  // 10: offers.v1.GetOffersByOrgIdResponse.offers:type_name -> offers.v1.Offer
	1,  // 11: offers.v1.GetOfferByIdResponse.offer:type_name -> offers.v1.Offer
	1,  // 12: offers.v1.CreateEmptyOfferResponse.offer:type_name -> offers.v1.Offer
	18, // 13: offers.v1.UpdateOfferRequest.positions:type_name -> positions.v1.Position
	19, // 14: offers.v1.UpdateOfferRequest.payment:type_name -> org.v1.Payment
	20, // 15: offers.v1.UpdateOfferRequest.discount:type_name -> positions.v1.Discount
	0,  // 16: offers.v1.UpdateOfferRequest.status:type_name -> offers.v1.OfferStatus
	1,  // 17: offers.v1.UpdateOfferResponse.offer:type_name -> offers.v1.Offer
	8,  // 18: offers.v1.OffersService.GetOffersByOrgId:input_type -> offers.v1.GetOffersByOrgIdRequest
	10, // 19: offers.v1.OffersService.GetOfferById:input_type -> offers.v1.GetOfferByIdRequest
	12, // 20: offers.v1.OffersService.CreateEmptyOffer:input_type -> offers.v1.CreateEmptyOfferRequest
	2,  // 21: offers.v1.OffersService.CreateOffer:input_type -> offers.v1.CreateOfferRequest
	4,  // 22: offers.v1.OffersService.GetOffersByCustomerId:input_type -> offers.v1.GetOffersByCustomerIdRequest
	6,  // 23: offers.v1.OffersService.GetOfferPdf:input_type -> offers.v1.GetOfferPdfRequest
	14, // 24: offers.v1.OffersService.UpdateOffer:input_type -> offers.v1.UpdateOfferRequest
	16, // 25: offers.v1.OffersService.DeleteOffer:input_type -> offers.v1.DeleteOfferRequest
	9,  // 26: offers.v1.OffersService.GetOffersByOrgId:output_type -> offers.v1.GetOffersByOrgIdResponse
	11, // 27: offers.v1.OffersService.GetOfferById:output_type -> offers.v1.GetOfferByIdResponse
	13, // 28: offers.v1.OffersService.CreateEmptyOffer:output_type -> offers.v1.CreateEmptyOfferResponse
	3,  // 29: offers.v1.OffersService.CreateOffer:output_type -> offers.v1.CreateOfferResponse
	5,  // 30: offers.v1.OffersService.GetOffersByCustomerId:output_type -> offers.v1.GetOffersByCustomerIdResponse
	7,  // 31: offers.v1.OffersService.GetOfferPdf:output_type -> offers.v1.GetOfferPdfResponse
	15, // 32: offers.v1.OffersService.UpdateOffer:output_type -> offers.v1.UpdateOfferResponse
	17, // 33: offers.v1.OffersService.DeleteOffer:output_type -> offers.v1.DeleteOfferResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_offers_v1_offers_proto_init() }
func file_offers_v1_offers_proto_init() {
	if File_offers_v1_offers_proto != nil {
		return
	}
	file_offers_v1_offers_proto_msgTypes[0].OneofWrappers = []any{}
	file_offers_v1_offers_proto_msgTypes[1].OneofWrappers = []any{}
	file_offers_v1_offers_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offers_v1_offers_proto_rawDesc), len(file_offers_v1_offers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offers_v1_offers_proto_goTypes,
		DependencyIndexes: file_offers_v1_offers_proto_depIdxs,
		EnumInfos:         file_offers_v1_offers_proto_enumTypes,
		MessageInfos:      file_offers_v1_offers_proto_msgTypes,
	}.Build()
	File_offers_v1_offers_proto = out.File
	file_offers_v1_offers_proto_goTypes = nil
	file_offers_v1_offers_proto_depIdxs = nil
}
